### ISSUE TITLE
ChangeLog - better feedback needed when no data

### ISSUE THREAD

**Issue by davidwatkins73** [khartec/waltz#1068]
![image](https://cloud.githubusercontent.com/assets/576829/20590826/553bab84-b21d-11e6-8fea-c0f40fc10e83.png)

**Comment by davidwatkins73** [comment]
Also, to make this mildly more interesting - is there a better way of representing this than our typical approach which I think is a bit ugly. 

![image](https://cloud.githubusercontent.com/assets/576829/20591172/17d59424-b21f-11e6-8bc7-d6e4060a632a.png)

 A new component with nicer styling is required - then we can roll that out across the site.

**Comment by davidwatkins73** [comment]
@rovats wanna have a think about this one ?

**Comment by rovats** [comment]
Yep, on it..

**Comment by rovats** [comment]
How about this:

![image](https://cloud.githubusercontent.com/assets/15289335/20597165/15e51764-b23a-11e6-8fe9-1c0a0cf7179e.png)

**Comment by davidwatkins73** [comment]
looks much better

**Comment by rovats** [comment]
Should I make this change across the site or only change log under this issue?

**Comment by davidwatkins73** [comment]
may as well do it across the site - however message may be better implemented as a transcluded content.  It will allow us to do 'call to action' links to remedy issues where appropriate.

````
<waltz-no-data>
   <message>No data</message>
</waltz-no-data>

<waltz-no-data>
  <message>
    No data, <a ui-sref='somewhere'>add one</a>
  </message>
</waltz-no-data>
