### ISSUE TITLE
High Phys Flows: Indexes required on

### ISSUE THREAD

**Issue by kamransaleem** [khartec/waltz#1075]
physical_flow: target id and kind
physical_specification: owning id and kind

**Comment by davidwatkins73** [comment]
not sure if this should go in 1.1.6 or 1.2.0  ......

**Comment by kamransaleem** [comment]
The difference in performance was significant. However we are retrieving
over 1mb of data in some of those requests and throwing a lot of it away.
Could perhaps make that more efficient too.

**Comment by davidwatkins73** [comment]
Lets.do that first.

**Comment by kamransaleem** [comment]
@kamransaleem
