### ISSUE TITLE
Person view : directs aren't alphabetical

### ISSUE THREAD

**Issue by davidwatkins73** [khartec/waltz#1189]

**Comment by davidwatkins73** [comment]
![image](https://cloud.githubusercontent.com/assets/576829/21007395/8f0c36ae-bd34-11e6-89d4-d03173875c5d.png)

**Comment by kamransaleem** [comment]
@kamransaleem

**Comment by davidwatkins73** [comment]
Do this via js, not via filter.  Need to avoid filters as much slower than sorting in controller.
