### ISSUE TITLE
Convert complexity breakdown into top 10 and full table on another tab.

### ISSUE THREAD

**Issue by davidwatkins73** [khartec/waltz#1222]
Similar to the cost approach.

**Comment by rovats** [comment]
WIP

**Comment by rovats** [comment]
![image](https://cloud.githubusercontent.com/assets/15289335/21773742/173fcf38-d688-11e6-83c6-e3f2b45c2b88.png)


![image](https://cloud.githubusercontent.com/assets/15289335/21773752/21d1624a-d688-11e6-94cc-d5d34e04bb1c.png)

**Comment by davidwatkins73** [comment]
Looks nice - we should use the same color scheme on asset costs.
