### ISSUE TITLE
ComplexityRatingDao.getForApp(): NullPointerException when the app has no associated scores

### ISSUE THREAD

**Issue by glorymanutd** [khartec/waltz#1228]
Some apps don't have associated servers, connections and capabilities (i.e. those in DEVELOPMENT) - so the method shouldn't throws NullPointerException but return NULL rating instead.

**Comment by glorymanutd** [comment]
@glorymanutd

**Comment by davidwatkins73** [comment]
Can you make the pull agains rel-1.1.x ?  (https://github.com/khartec/waltz/tree/rel-1.1.x)

**Comment by davidwatkins73** [comment]
Merge into master
