### ISSUE TITLE
Changelog: Modify code to populate CHILD_KIND and OPERATION columns

### ISSUE THREAD

**Issue by rovats** [khartec/waltz#1328]

**Comment by davidwatkins73** [comment]
It could be that adding `child_id` complicates for little additional benefit.

**Comment by rovats** [comment]
Yes Operation will be an enum.

Yeah we don't actually need `child_id` right now, since the message would be enough to send out notifications. The only benefit would be that if in future we want to show a history per `child_id`, we would be able to.

**Comment by rovats** [comment]
Also, we are thinking of setting the `Operation` as being applied to the `child_kind` instead of the `parent_kind`.

For example, adding a bookmark to an application will have the `operation` as `Add`/`Create` instead of `Update` (the app is being updated).

Otherwise, 99% of the cases, the operation will always be `Update`

Thoughts?
