### ISSUE TITLE
[Physical Flow] Confirmed column to differentiate bulk inserted flow from a confirmed one

### ISSUE THREAD

**Issue by kamransaleem** [khartec/waltz#1366]
When a set of physical flows are created by the CSV bulk loader, the provenance is set to indicate the  source file.  The physical flow can later be referred to i.e. in a lineage report, mentions in other flows, bookmark edits etc.  There is presently no reliable way to ascertain the flow has implicitly been '**confirmed**' by it's mention or usage elsewhere.

If a bulk re-insert is required, we cannot then safely delete previously inserted flows from a particular source file in case they have been confirmed.

**Proposal**
- `confimed_by` and `confirmed_at` columns added to `physical_flow`, `physical_specification`, `logical_flow tables`.
- when bulk inserted, `confirmed_by` will be set to `'batch_loader'`, `confirmed_at` the time of insert and `provenance` will indicate the source file
- when a physical flow is mentioned, it's `confirmed_by` value will be changed to the user who initiated the change.  `confimed_at` will be set appropriately.
- if a bulk re-insert is carried out, the flows which are confirmed by other users will not be replaced

(edit: dw - formatting)

**Comment by davidwatkins73** [comment]
@rovats @glorymanutd - thoughts ?

**Comment by rovats** [comment]
Will the `confirmed_by` only change when a flow is mentioned? If yes, can we not just check that a flow is mentioned in a lineage, and thus has implicitly been confirmed?

**Comment by kamransaleem** [comment]
Or if a bookmark is added to the flow, or even if the logical flow that it is linked to has a datatype modification from unknown to something else.  Basically any use initiated action which indicates that the flow has been seen and implicitly 'validated'.

**Comment by kamransaleem** [comment]
Had another think about this as I was about to start implementing.  This feels like a poor mans attestation.
Spoke with @rovats  and we thought of a generic solution which has less impact on existing tables and is more functional.

**Proposed solution:**
Create an 'attestation' table with the following columns:
`entity_kind | entity_id | attestation_type | attestation_date | attested_by | comments`

where `attestation_type` is an enum with the values `EXPLICIT` or `IMPLICIT`.

**Benefits:**
- columns are not required for every table / entity that needs this type of functionality
- more than one type of 'attestation' can be supported
- no impact on existing tables, immutables etc.

**Comment by davidwatkins73** [comment]
Thats a good idea.  Agree that it will result in a nicer impl.

**Comment by kamransaleem** [comment]
This will be just the table.  Will separate the code changes to keep the
changes smaller. Have created a separate issue to deal with the flow and
spec attestations

**Comment by davidwatkins73** [comment]
Thanks

**Comment by kamransaleem** [comment]
milestone: 1.2

**Comment by davidwatkins73** [comment]
thanks
