### ISSUE TITLE
Source Data Rating call error

### ISSUE THREAD

**Issue by kamransaleem** [khartec/waltz#1478]
/api/source-data-rating

Exception: No enum constant com.khartec.waltz.model.EntityKind.CAPABILITY / java.lang.IllegalArgumentException

**Comment by davidwatkins73** [comment]
What page was this on ?

**Comment by kamransaleem** [comment]
It should be on any page which retrieves source data ratings. Prod has a
capability Source Data Rating and it throws because the entity kind enum
doesn't.

**Comment by davidwatkins73** [comment]
ah got it - was looking for a call to it.  I remember now - it reads them all and we filter client side.
