### ISSUE TITLE
Survey: UI - display logged in user's surveys

### ISSUE THREAD

**Issue by rovats** [khartec/waltz#1514]
* Display survey instances that the user needs to fill along with their status
* Change the survey link in the `mailto` link

**Comment by rovats** [comment]
![image](https://cloud.githubusercontent.com/assets/15289335/22736301/5e848bfc-edf5-11e6-9f7e-906b9d8e9312.png)

**Comment by davidwatkins73** [comment]
Would `Survey Subject`be cleared than `Survey Entity` - your call.
