### ISSUE TITLE
[Physical Specification] Prevent duplicate specifications being created for the same owning entity

### ISSUE THREAD

**Issue by kamransaleem** [khartec/waltz#1527]

**Comment by kamransaleem** [comment]
user interface already prevents duplicate specs being created:

![image](https://cloud.githubusercontent.com/assets/3029467/22932856/552e5030-f2c1-11e6-9782-15c6313d1e1d.png)

**Comment by davidwatkins73** [comment]
perhaps - but think more pressing issues at the mo'.   Will raise this as a new issue
