### ISSUE TITLE
Survey: response edit - improve validation

### ISSUE THREAD

**Issue by rovats** [khartec/waltz#1546]
* Highlight fields with errors
* Hide submit button if there are errors
* Add a Save For Later button
* Add confirmation on submit

**Comment by davidwatkins73** [comment]
Something like this may help:

````
angular.module('anchorScrollOffsetExample', [])
.run(['$anchorScroll', function($anchorScroll) {
  $anchorScroll.yOffset = 50;   // always scroll by 50 extra pixels
}])
````
[Source](https://docs.angularjs.org/api/ng/service/$anchorScroll)

**Comment by rovats** [comment]
fixed (test and close)
