### ISSUE TITLE
Application Complexity (OU) table - still refers to characteristics

### ISSUE THREAD

**Issue by davidwatkins73** [khartec/waltz#1574]

**Comment by davidwatkins73** [comment]
![image](https://cloud.githubusercontent.com/assets/576829/22933456/9a6997d4-f2c3-11e6-8133-e01f4d51fccb.png)

**Comment by kamransaleem** [comment]
Should this column be removed outright?

**Comment by davidwatkins73** [comment]
We still calculate it - but it's now based on the entire collection of measurables an application is registered against.   We haven't used the word measurables in the ui - hence going with `Viewpoints`.

At some point I think we probably want to convert `ComplexityKind` from an enum into a reference table so that organisations can chose what metrics they wish to use when calculating complexiy.  That would mean the grid would need dynamic column headings.
