### ISSUE TITLE
Grid: min-height should be removed

### ISSUE THREAD

**Issue by rovats** [khartec/waltz#1577]
Added by #1326 

This prevents dynamic sizing of the grid based on the number of data rows.

**Comment by davidwatkins73** [comment]
This was needed to workaround the following scenario:

- table configured with 3 rows of data
- a nice small table is created
- something causes a load more data to be displayed
- table does not resize so now looking at a large dataset through a 3 row viewport.

May be able to solve by destroying and recreating table or similar.  If tackled ensure export facility is still working.
