### ISSUE TITLE
Survey: should display 'unknown' for owners/participants no longer exist

### ISSUE THREAD

**Issue by glorymanutd** [khartec/waltz#1719]

**Comment by rovats** [comment]
* Single participant no longer exists - display Unknown
* Multiple participants and they all no longer exist - display Unknown
* Multiple participants and some exist - Show the ones that exist

**Comment by glorymanutd** [comment]
@glorymanutd

**Comment by glorymanutd** [comment]
Not easy to get the unknown participants back for a survey instance as SurveyInstanceRecipientDao.findForSurveyInstance uses an inner join to Person table.

Left join here would result all-null people which can't be constructed by the immutable builder.

**Comment by glorymanutd** [comment]
Fixed for non-existing owners for now. Will create another ticket for participants as it required more changes.
