### ISSUE TITLE
Physical flow editor does not prevent attempts to create self-loops

### ISSUE THREAD

**Issue by davidwatkins73** [khartec/waltz#1773]

**Comment by kamransaleem** [comment]
**Cannot reproduce.**

The physical flow editor only allows selection of a target based on an existing logical flow

<img width="279" alt="waltz__register_new_physical_flow" src="https://cloud.githubusercontent.com/assets/3029467/25329623/755d2662-28d4-11e7-96cb-79a217b1170f.png">

The logical flow editor prevents self loops already via a notification:

![waltz__register_logical_data_flows](https://cloud.githubusercontent.com/assets/3029467/25329671/b06e6b80-28d4-11e7-9d11-0adb43797edd.png)
