### ISSUE TITLE
Physical Flow Delete button still active when disabled

### ISSUE THREAD

**Issue by davidwatkins73** [khartec/waltz#1774]
However deletion rejected by server w/ notification.

![image](https://cloud.githubusercontent.com/assets/576829/23557057/9c4196ae-0026-11e7-9f6c-c6b40176c519.png)

**Comment by rovats** [comment]
@rovats

**Comment by rovats** [comment]
<img width="378" alt="screen shot 2017-03-08 at 12 01 46" src="https://cloud.githubusercontent.com/assets/15289335/23703286/156c5d9c-03f7-11e7-948b-d903b245dd28.png">

`waltz-has-role` replaces the button with a `span`, and `ng-disabled` only works on `buttons`.
Also, when an element is disabled, no mouse events are fired, hence the little icon next to the button to show the tooltip.
