### ISSUE TITLE
Logical flow decorator rating call fails

### ISSUE THREAD

**Issue by rovats** [khartec/waltz#1984]
If there is a flow marked as removed.

the `is_removed` filter should be applied when fetching decorators as well.

**Comment by davidwatkins73** [comment]
can you provide more details on where this happens - struggling to recreate.

**Comment by rovats** [comment]
happens on int1, NPE on the following line in `LogicalFlowDecoratorRatingsCalculator` as per logs:

`Application targetApp = targetAppsById.get(flow.target().id());`
