### ISSUE TITLE
Phys Spec - full text search

### ISSUE THREAD

**Issue by davidwatkins73** [khartec/waltz#2000]
Use a proper full text search index against physical specifications

Relates to  #1996

**Comment by davidwatkins73** [comment]
Woohoo Issue 2000!   ;)

**Comment by kamransaleem** [comment]
I don't know if this is best suited for full text.  The SQL server full text requires completed words, whereas the current implementation works with 'contains'.  Because spec names are often one word with - or _ separators.  Will using full text make it less searchable?

**Comment by davidwatkins73** [comment]
Agreed, closing - thanks
