### ISSUE TITLE
Spec File: allow direct altering of status

### ISSUE THREAD

**Issue by davidwatkins73** [khartec/waltz#2017]
see #1994

**Comment by davidwatkins73** [comment]
@rovats

**Comment by kamransaleem** [comment]
Buttons on the below component:
<img width="188" alt="waltz__regulatory-credit-1_doc" src="https://cloud.githubusercontent.com/assets/3029467/25172765/e588a202-24e9-11e7-8b78-0d0a6b5ec0ce.png">


State machine as follows:
![img_0111](https://cloud.githubusercontent.com/assets/3029467/25172657/a21729c6-24e9-11e7-8a8e-e0cccd909842.JPG)
