### ISSUE TITLE
Measurable tabs - make it clearer which is the selected tab

### ISSUE THREAD

**Issue by kamransaleem** [khartec/waltz#2230]
perhaps a empty circle before each tab header which gets filled for the selected tab

Could apply all round?

**Comment by rovats** [comment]
@rovats

**Comment by rovats** [comment]
GitHub style top border?:

![image](https://cloud.githubusercontent.com/assets/15289335/26581334/ea86ee66-4533-11e7-8154-11e40e6d60f9.png)
