### ISSUE TITLE
Flow Diagram View: Changes section

### ISSUE THREAD

**Issue by davidwatkins73** [khartec/waltz#2240]
Parent #2185

**Comment by rovats** [comment]
@rovats

**Comment by davidwatkins73** [comment]
Would it be possible to make this lazy by default (i.e. click to show change log) ?

**Comment by rovats** [comment]
Yep, should be doable. I've made most of the changes for this (23 files). Is it worth committing those to minimise conflicts and doing this in another issue?

I can also cleanup deprecated usages of the ChangeLogStore in the new issue.

**Comment by davidwatkins73** [comment]
yup agree - better to commit now and patch later.
