### ISSUE TITLE
Move Entity Named Notes into own section

### ISSUE THREAD

**Issue by davidwatkins73** [khartec/waltz#2324]
Section called `Additional Notes`

Hide section if no notes & unable to add them

**Comment by davidwatkins73** [comment]
Is it possible to get something pushed in for this quite soon? - MG is demoing @ 1pm

**Comment by kamransaleem** [comment]
Working on this now, ETA 30mins or so

**Comment by davidwatkins73** [comment]
great - thx

**Comment by kamransaleem** [comment]
Add note button in section now and tightened up the spacing a bit by removing the excess line breaks.  If it's still too big probably needs more rework.
