### ISSUE TITLE
Attestation: DDL

### ISSUE THREAD

**Issue by rovats** [khartec/waltz#2474]
* New `Attestation` table:
** Parent Entity (App only for now?)
** Child Kind (Logical Flows, Physical Flows)
** Attested on
** Attested By
** Comments (optional?)

Open Questions:
* Do we keep history of attestations?
* Add `last_attested_at` and `last_attested_by` on child kind tables and set them?

**Comment by davidwatkins73** [comment]
a) yes - think we probably should.  I feel like we'll end up with an attestation run table at some point (like surveys)
b) y, don't want to have to join for attestation status

**Comment by rovats** [comment]
@davidwatkins73 Should this new attestation system be merged with the existing `attestation` table? Or do we get rid of the existing table?

**Comment by davidwatkins73** [comment]
Probably drop and recreate - don't think anyone is using it for anything (other than our internal code) - may be worth checking with @kamransaleem
