### ISSUE TITLE
asset_cost: `kind`s should be defined at system level

### ISSUE THREAD

**Issue by davidwatkins73** [khartec/waltz#2530]
via `enum_value` table

**Comment by rovats** [comment]
@rovats

**Comment by davidwatkins73** [comment]
To hit, this should be similar to the approach taken with bookmark kinds

**Comment by davidwatkins73** [comment]
Damn autocorrect!  Rohit not 'to hit'!

**Comment by rovats** [comment]
:) 
Yes, insert them into `enum_value` table, then use `<waltz-enum-value>` in the templates, right?

**Comment by davidwatkins73** [comment]
Yup. Think that's it
