### ISSUE TITLE
Error when adding an app to app group

### ISSUE THREAD

**Issue by kamransaleem** [khartec/waltz#2714]
`Exception: SQL [select [rel].[id], [rel].[name], [rel].[description], [rel].[asset_code], [rel].[created_at], [rel].[updated_at], [rel].[organisational_unit_id], [rel].[kind], [rel].[lifecycle_phase], [rel].[parent_asset_code], [rel].[overall_rating], [rel].[provenance], [rel].[business_criticality], [rel].[is_removed], [rel].[entity_lifecycle_status] from [application] [rel] join [application] [self] on ([rel].[asset_code] = [self].[asset_code] or ([rel].[parent_asset_code] = [self].[parent_asset_code] and [self].[parent_asset_code] <> ?) or [rel].[parent_asset_code] = [self].[asset_code] or ([rel].[asset_code] = [self].[parent_asset_code] and [self].[parent_asset_code] <> ?)) where ([self].[id] = ? and [application].[entity_lifecycle_status] = ?)]; The multi-part identifier "application.entity_lifecycle_status" could not be bound. / org.jooq.exception.DataAccessException`

**Comment by davidwatkins73** [comment]
Cannot recreate - can this be closed ?

**Comment by kamransaleem** [comment]
Yes, this was a one liner fixed as part of #703

**Comment by davidwatkins73** [comment]
thanks
