### ISSUE TITLE
Flow Diagrams: link to CI's

### ISSUE THREAD

**Issue by davidwatkins73** [khartec/waltz#2761]

**Comment by kamransaleem** [comment]
@kamransaleem

**Comment by davidwatkins73** [comment]
Hi Kamran - I've been looking at this (but it's exploded in complexity as I tried to pull out the sections into different components....)

**Comment by kamransaleem** [comment]
no worries, I'll leave it to you ;)

**Comment by davidwatkins73** [comment]
the way it's going we may need a plan B ;)

**Comment by kamransaleem** [comment]
do we have a plan B? ;)

**Comment by davidwatkins73** [comment]
Massive amounts of tea are slowly massaging the neurons into sorting this tangle out.  Painful but worth it.
