### ISSUE TITLE
packages are missing.

### ISSUE THREAD

**Issue by RajeshAnviam** [khartec/waltz#2782]
1) I'm able to configure the relation between projects. but for project "waltz-schema" the below package is missing.
"com.khartec.waltz.schema.tables".

2) for project "waltz-model" the Immutable_* classes are missing.

**Comment by davidwatkins73** [comment]
The classes you mention are generated during the [build](https://github.com/khartec/waltz/blob/master/docs/build.md) process.

They are the output from the [Immutables](https://immutables.github.io/) library and from [jOOQ](https://www.jooq.org/)

**Comment by RajeshAnviam** [comment]
Hello David Watkins

Thank you very much for the reply,
I have checked the doc and try to build the application via Travis.
As my understanding I need database structure for JOOQ, the JOOQ will
generate java class from the database structure. generate where we mention
the packages for java class.

*kindly request please mention the database exported script location.*

below links are not mentioning the database architecture.

https://github.com/davidwatkins73/waltz-dev/blob/master/docs/features/entity_notes/entity_notes_schema.txt
https://github.com/davidwatkins73/waltz-dev/blob/master/docs/features/flow_diagrams/flow_diagram_schema.txt
https://github.com/davidwatkins73/waltz-dev/blob/master/docs/features/logical_flows/logical_flows_schema.png

*kindly request please suggest.*

Regards,
Rajesh Gupta

**Comment by davidwatkins73** [comment]
The build process ensures the database has the correct version of the schema - it uses liquibase to apply the DDL.

**Comment by RajeshAnviam** [comment]
Hello David Watkins,

Really thank you for the guidance.
I was able to setup the project.
but while doing changes, the changes are not reflected.

when i did the changes and try to run waltz-ng project's "dev-server.sh"
file. the old data are reflected.
*please suggest how to check the changes.*

Regards,
Rajesh Gupta

**Comment by davidwatkins73** [comment]
Could you raise a more specific issue detailing what you are trying to achieve and what issues you are encountering ? Thanks.
