### ISSUE TITLE
Revert CI status filter

### ISSUE THREAD

**Issue by davidwatkins73** [khartec/waltz#2797]
Causing confusing behaviour

**Comment by kamransaleem** [comment]
removing 
`private final Condition liveCis = CHANGE_INITIATIVE.START_DATE.le(toSqlDate(nowUtc().toLocalDate()))
            .and(CHANGE_INITIATIVE.END_DATE.ge(toSqlDate(nowUtc().toLocalDate())))
            .and(CHANGE_INITIATIVE.LIFECYCLE_PHASE.notEqual(LifecyclePhase.RETIRED.name()));`
