### ISSUE TITLE
CSV Mulitline exports breaking when region/format is set to 'German'

### ISSUE THREAD

**Issue by davidwatkins73** [khartec/waltz#2824]
![image](https://user-images.githubusercontent.com/576829/32843307-5bb22d04-ca17-11e7-8bf8-1bb1197b2be8.png)

**Comment by rovats** [comment]
`CsvPreference.EXCEL_NORTH_EUROPE_PREFERENCE` works correctly with the above settings.
We can probably use the `Accept-Language` header to decide which preference to use.

With the above settings, IE sends the header value correctly as `de-DE`, but Chrome doesn't.

**Comment by davidwatkins73** [comment]
did you restart Chrome ? perhaps it's only read once at startup...

**Comment by rovats** [comment]
Restarting also doesn't help. I think `navigator.language` in Chrome is always the language set in the browser.

On IE, the `navigator` object has a `userLanguage` field which stores the system language, and looks like that is what is sent as the header
