### ISSUE TITLE
Flow Diagram: Creating new diagram for a measurable throws error

### ISSUE THREAD

**Issue by rovats** [khartec/waltz#2841]
Error:

`Don't know how to create starter flow diagram commands for entity ref Object {id: 10, kind: "MEASURABLE", name: "Balance Services"}`

`TypeError: flowDiagramStarterService.mkCommands(...).then is not a function
    at controller.vm.onCreateDiagram (flow-diagrams-panel.js:102)
    at fn (eval at compile (angular.js:15126), <anonymous>:4:279)
    at expensiveCheckFn (angular.js:16213)
    at callback (angular.js:26592)
    at ChildScope.$eval (angular.js:17994)
    at ChildScope.$apply (angular.js:18094)
    at HTMLAnchorElement.<anonymous> (angular.js:26597)
    at defaultHandlerWrapper (angular.js:3546)
    at HTMLAnchorElement.eventHandler (angular.js:3534)`

**Comment by davidwatkins73** [comment]
Hmm, I think we previously prevented starting a diagram on a measurable page as there isn't anything we can draw to start the diagram off.....   I'll take a look.

**Comment by rovats** [comment]
Seems to work fine, but just throws an error initially

**Comment by davidwatkins73** [comment]
Suppose we could just provide a default 'do-nothing' starter command fn.  That would prevent the initial error.

**Comment by davidwatkins73** [comment]
Feel free to take a look if you want - as I won't get round to it today....

**Comment by rovats** [comment]
Yeah, not a big issue.. I thought there was something wrong when I first saw the error, but for measurables there is nothing to draw by default.. will take a look to see if we can prevent it.

**Comment by davidwatkins73** [comment]
There's a factory service somewhere for creating the starter commands....

**Comment by rovats** [comment]
Yep, the js error goes away by changing:

`return []`
to:
`return Promise.resolve([]);`

But the server throws a silent error, because diagram name is not set by default, I'll add a default command to set name.
