### ISSUE TITLE
Missing copyright/license terms from 3rd party authors

### ISSUE THREAD

**Issue by maxbrito** [khartec/waltz#3003]
Hello,

I've noticed that for many of the third-party libraries such as:
https://github.com/khartec/waltz/blob/master/waltz-ng/client/common/d3-context-menu.js

There is a URL pointing to the original source, however, there is no mentioning of the original copyright author nor the original license terms that were attached:
https://github.com/pkerpedjiev/d3-context-menu/blob/master/LICENSE.txt

The license terms for MIT specifically requests:
> The above copyright notice and this permission notice shall be included in
> all copies or substantial portions of the Software.

Perhaps possible to add on the header of such files the MIT license terms with the author name instead of the LGPL reference to avoid confusion when creating a 3rd party inventory list?

Many thanks.

**Comment by kamransaleem** [comment]
Thank you for raising this.  Prioritised for the 1.9.
