### ISSUE TITLE
Entity enums

### ISSUE THREAD

**Issue by rovats** [khartec/waltz#3030]
To support custom properties on entities.

* New table `entity_enum_definition`
** `id`
** `entityKind`
** `name`
** `description`
** `icon`
** `enumValueType`
** `editable`

* New table `entity_enum_value`
** `definition_id`
** `entityReference`
** `enumValueKey`
** `lastUpdated`
** `provenance`

* Display on entity page (start with Change initiative)

**Comment by kamransaleem** [comment]
@davidwatkins73 this looks complete
