### ISSUE TITLE
Trying to do Maven Build in Eclipse , getting Liquibase Error

### ISSUE THREAD

**Issue by SteveRedeem** [khartec/waltz#3186]
Has anyone seen this before? Whatever could this mean? 

[ERROR] Failed to execute goal org.liquibase:liquibase-maven-plugin:3.5.1:update (default) on project waltz-schema: 
Error setting up or running Liquibase: liquibase.exception.DatabaseException: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=127.0.0.1)(port=3306)(type=master) : Connection refused: connect -> [Help 1]

**Comment by davidwatkins73** [comment]
Waltz uses [jOOQ](https://www.jooq.org/) for it's data access.  During the build phase we generate code based upon the Waltz schema.  This schema is, in turn, managed by [Liquibase](https://www.liquibase.org/) and as part of the build process we run liquibase to ensure the schema of your database instance matches that required by the Waltz code base.  

Currently we support Maria and MSSQL databases.  The error looks like it's failing to connect to the default database (maria on localhost). The following two files give a bit more information about configuring database support in Waltz.

- [Building](https://github.com/khartec/waltz/blob/master/docs/build.md)
- [Running](https://github.com/khartec/waltz/blob/master/waltz-web/README.md)

**Comment by davidwatkins73** [comment]
Closing, feel free to open a new issue if the above suggestion did not fix the problem.
