### ISSUE TITLE
Document: add lightweight architecture decision records

### ISSUE THREAD

**Issue by davidwatkins73** [khartec/waltz#3518]
See this [article by Michael Nygard](http://thinkrelevance.com/blog/2011/11/15/documenting-architecture-decisions)

**Comment by davidwatkins73** [comment]
Nat Pryces's [scripts](https://github.com/npryce/adr-tools) seem to be a good starting point

**Comment by kamransaleem** [comment]
Great idea.

Starting with a table with the following:

```
Title | Context | Decision | Status | Consequences 
```

**Comment by davidwatkins73** [comment]
These are kinda done via our design notes section in the docs
