### ISSUE TITLE
Is it possible to do LDAP integration?

### ISSUE THREAD

**Issue by seanradley** [khartec/waltz#3523]
Hi @davidwatkins73 

I'd like to use LDAP credentials to log into Waltz. Is that possible right now?

Thanks

**Comment by davidwatkins73** [comment]
It's not an integration we've done yet.   We have some documentation around configuring authentication in the [security settings] (https://github.com/khartec/waltz/blob/master/docs/features/configuration/settings.md#security) document.

Within Waltz the authentication is setup in the [`com.khartec.waltz.web.endpoints.auth.AuthenticationEndpoint`](https://github.com/khartec/waltz/blob/master/waltz-web/src/main/java/com/khartec/waltz/web/endpoints/auth/AuthenticationEndpoint.java)

**Comment by rovats** [comment]
This is now possible. Documentation here:
https://github.com/khartec/waltz/blob/master/docs/integration/external-authentication/external-authentication.md
