### ISSUE TITLE
Support Postgres (again)

### ISSUE THREAD

**Issue by davidwatkins73** [khartec/waltz#3599]
Need to figure out what a good baseline version to target is.

**Comment by davidwatkins73** [comment]
10.x seems to be the current stable version.  Will target that.

**Comment by davidwatkins73** [comment]
Maven profiles:

```
      <profile>
            <id>waltz-postgres</id>
            <properties>
                <jdbc.group>org.postgresql</jdbc.group>
                <jdbc.artifact>postgresql</jdbc.artifact>
                <jdbc.version>42.2.5</jdbc.version>
                <jdbc.driver>org.postgresql.Driver</jdbc.driver>
                <jooq.dialect>POSTGRES</jooq.dialect>
                <jooq.group>org.jooq</jooq.group>
                <jooq.database>org.jooq.util.postgres.PostgresDatabase</jooq.database>
                <database.catalog></database.catalog> <!-- only required for MSSQL -->
            </properties>
        </profile>
        <profile>
            <id>dev-postgres</id>
            <properties>
                <database.url>jdbc:postgresql://localhost:5432/waltz</database.url>
                <database.user>postgres</database.user>
                <database.password>password</database.password>
                <database.schema>public</database.schema>
            </properties>
        </profile>
```

**Comment by davidwatkins73** [comment]
Quick test indicates that we may have a small problem with index names.  They need to be unique within a pg schema:

> `ERROR: relation "idx_asset_code" already exists [Failed SQL: CREATE INDEX idx_asset_code ON server_information(asset_code)]`

**Comment by davidwatkins73** [comment]
Tip: although not really well documented, the `dbms` predicate accepts a comma separated list, e.g. `mssql,mysql`.

**Comment by davidwatkins73** [comment]
The above commit is a starting point.  Not yet merged into mainline.   `db.changelog-1.0.xml` is ported.  Other  changelog files should adopt a similar approach.

**Comment by kamransaleem** [comment]
> Quick test indicates that we may have a small problem with index names. They need to be unique within a pg schema:
> 
> > `ERROR: relation "idx_asset_code" already exists [Failed SQL: CREATE INDEX idx_asset_code ON server_information(asset_code)]`
> 
> This should be fixable using liquibase predicates and adopting a tablename prefixed indexname for pg.

how about idx_<table>_<columns>

**Comment by davidwatkins73** [comment]
> > Quick test indicates that we may have a small problem with index names. They need to be unique within a pg schema:
> > > `ERROR: relation "idx_asset_code" already exists [Failed SQL: CREATE INDEX idx_asset_code ON server_information(asset_code)]`
> > 
> > 
> > This should be fixable using liquibase predicates and adopting a tablename prefixed indexname for pg.
> 
> how about `idx_[table]_[columns]`

Unfortunately in postgres the names need to be unique across all the tables, hence we'll need a table specific prefix.
