### ISSUE TITLE
Housekeeping: upgrade jOOQ

### ISSUE THREAD

**Issue by davidwatkins73** [khartec/waltz#3634]

**Comment by rovats** [comment]
Note, in v3.11.7, package names have changed a bit.

E.g.: in `waltz-schema` `pom` file, we'll need to change:
`org.jooq.util.sqlserver.SQLServerDatabase`
to
`org.jooq.meta.sqlserver.SQLServerDatabase`

**`util`** has changed to **`meta`** for these classes

**Comment by davidwatkins73** [comment]
@kamransaleem  @rovats 
Quick vote, shall we do this now or wait for 1.16 ?

**Comment by kamransaleem** [comment]
Let’s wait until early in next release.  Seems like there may be some breaking changes.

**Comment by rovats** [comment]
Probably best to do it in the first week of v1.16 dev.

**Comment by davidwatkins73** [comment]
v3.11.9 is latest - going with that.
