### ISSUE TITLE
Getting erro while building schema package

### ISSUE THREAD

**Issue by ajaymohad123** [khartec/waltz#3657]
Hi...

I am getting error while building schema package using jooq codegen 

Exception in main thread "java.lang.InternalError"
Error occured while invoking reflection on target classes. Make sure all referenced classes are on classpath. interface javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter.

any suggestion help? what is going wrong?

Regards,
Ajay

**Comment by davidwatkins73** [comment]
Hi Ajay,
Would it be be possible for you to give us a few more details about your environment:

- java version
- maven version
- database version
- any stack trace
 etc.

?  

Thanks,
Dave

**Comment by ajaymohad123** [comment]
Hi Dave..

Thanks for the quick response... below are the details...

Java version - jdk1.8.0_191
maven - apache-maven-3.2.2
database - mariadb-10.3.11-winx64

stack trace..

[DEBUG] Configuring mojo org.jooq:jooq-codegen-maven:3.10.7:generate from plugin realm ClassRealm[plugin>org.jooq:jooq-codegen-maven:3.10.7, parent: sun.misc.Launcher$AppClassLoader@4e25154f]
[DEBUG] Configuring mojo 'org.jooq:jooq-codegen-maven:3.10.7:generate' with basic configurator -->
[DEBUG]   (s) name = org.jooq.util.mariadb.MariaDBDatabase
[DEBUG]   (s) inputSchema = waltz456
[DEBUG]   (s) outputSchemaToDefault = true
[DEBUG]   (s) database = org.jooq.util.jaxb.Database@191c6e13
[DEBUG]   (s) packageName = com.khartec.waltz.schema
[DEBUG]   (s) directory = target/generated-sources/jooq
[DEBUG]   (s) target = org.jooq.util.jaxb.Target@1a8e9ed9
[DEBUG]   (f) generator = org.jooq.util.jaxb.Generator@68ea253b
[DEBUG]   (s) driver = org.mariadb.jdbc.Driver
[DEBUG]   (s) url = jdbc:mysql://localhost:3306/waltz456
[DEBUG]   (s) user = root
[DEBUG]   (s) password = ajay1975
[DEBUG]   (f) jdbc = org.jooq.util.jaxb.Jdbc@57bd6a8f
[DEBUG]   (f) project = MavenProject: com.khartec:waltz-schema:1.0-SNAPSHOT @ C:\Users\10640921\git\waltznew\waltz-schema\pom.xml
[DEBUG] -- end configuration --
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:49 min
[INFO] Finished at: 2018-12-07T21:48:12+05:30
[INFO] Final Memory: 14M/218M
[INFO] ------------------------------------------------------------------------
Exception in thread "main" ---------------------------------------------------
constituent[0]: file:/D:/eclipse/configuration/org.eclipse.osgi/281/0/.cp/
constituent[1]: file:/D:/apache-maven-3.2.2/lib/aether-api-0.9.0.M2.jar
constituent[2]: file:/D:/apache-maven-3.2.2/lib/aether-connector-wagon-0.9.0.M2.jar
constituent[3]: file:/D:/apache-maven-3.2.2/lib/aether-impl-0.9.0.M2.jar
constituent[4]: file:/D:/apache-maven-3.2.2/lib/aether-spi-0.9.0.M2.jar
constituent[5]: file:/D:/apache-maven-3.2.2/lib/aether-util-0.9.0.M2.jar
constituent[6]: file:/D:/apache-maven-3.2.2/lib/aopalliance-1.0.jar
constituent[7]: file:/D:/apache-maven-3.2.2/lib/cdi-api-1.0.jar
constituent[8]: file:/D:/apache-maven-3.2.2/lib/commons-cli-1.2.jar
constituent[9]: file:/D:/apache-maven-3.2.2/lib/commons-io-2.2.jar
constituent[10]: file:/D:/apache-maven-3.2.2/lib/commons-lang-2.6.jar
constituent[11]: file:/D:/apache-maven-3.2.2/lib/guava-14.0.1.jar
constituent[12]: file:/D:/apache-maven-3.2.2/lib/javax.inject-1.jar
constituent[13]: file:/D:/apache-maven-3.2.2/lib/jaxb-api-2.0.jar
constituent[14]: file:/D:/apache-maven-3.2.2/lib/jaxb-api-2.2.10.jar
constituent[15]: file:/D:/apache-maven-3.2.2/lib/jsoup-1.7.2.jar
constituent[16]: file:/D:/apache-maven-3.2.2/lib/jsr250-api-1.0.jar
constituent[17]: file:/D:/apache-maven-3.2.2/lib/maven-aether-provider-3.2.2.jar
constituent[18]: file:/D:/apache-maven-3.2.2/lib/maven-artifact-3.2.2.jar
constituent[19]: file:/D:/apache-maven-3.2.2/lib/maven-compat-3.2.2.jar
constituent[20]: file:/D:/apache-maven-3.2.2/lib/maven-core-3.2.2.jar
constituent[21]: file:/D:/apache-maven-3.2.2/lib/maven-embedder-3.2.2.jar
constituent[22]: file:/D:/apache-maven-3.2.2/lib/maven-model-3.2.2.jar
constituent[23]: file:/D:/apache-maven-3.2.2/lib/maven-model-builder-3.2.2.jar
constituent[24]: file:/D:/apache-maven-3.2.2/lib/maven-plugin-api-3.2.2.jar
constituent[25]: file:/D:/apache-maven-3.2.2/lib/maven-repository-metadata-3.2.2.jar
constituent[26]: file:/D:/apache-maven-3.2.2/lib/maven-settings-3.2.2.jar
constituent[27]: file:/D:/apache-maven-3.2.2/lib/maven-settings-builder-3.2.2.jar
constituent[28]: file:/D:/apache-maven-3.2.2/lib/org.eclipse.sisu.inject-0.0.0.M5.jar
constituent[29]: file:/D:/apache-maven-3.2.2/lib/org.eclipse.sisu.plexus-0.0.0.M5.jar
constituent[30]: file:/D:/apache-maven-3.2.2/lib/plexus-cipher-1.7.jar
constituent[31]: file:/D:/apache-maven-3.2.2/lib/plexus-component-annotations-1.5.5.jar
constituent[32]: file:/D:/apache-maven-3.2.2/lib/plexus-interpolation-1.19.jar
constituent[33]: file:/D:/apache-maven-3.2.2/lib/plexus-sec-dispatcher-1.3.jar
constituent[34]: file:/D:/apache-maven-3.2.2/lib/plexus-utils-3.0.17.jar
constituent[35]: file:/D:/apache-maven-3.2.2/lib/sisu-guice-3.1.3-no_aop.jar
constituent[36]: file:/D:/apache-maven-3.2.2/lib/slf4j-api-1.7.5.jar
constituent[37]: file:/D:/apache-maven-3.2.2/lib/slf4j-simple-1.7.5.jar
constituent[38]: file:/D:/apache-maven-3.2.2/lib/stax-api-1.0-2.jar
constituent[39]: file:/D:/apache-maven-3.2.2/lib/wagon-file-2.6.jar
constituent[40]: file:/D:/apache-maven-3.2.2/lib/wagon-http-2.6-shaded.jar
constituent[41]: file:/D:/apache-maven-3.2.2/lib/wagon-http-shared-2.6.jar
constituent[42]: file:/D:/apache-maven-3.2.2/lib/wagon-provider-api-2.6.jar
constituent[43]: file:/D:/apache-maven-3.2.2/conf/logging/
---------------------------------------------------
java.lang.InternalError: 
Error occured while invoking reflection on target classes. Make sure all referenced classes are on classpath: interface javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter 
Exception: null
	at com.sun.xml.internal.bind.v2.model.annotation.RuntimeInlineAnnotationReader.getClassValue(RuntimeInlineAnnotationReader.java:128)
	at com.sun.xml.internal.bind.v2.model.annotation.RuntimeInlineAnnotationReader.getClassValue(RuntimeInlineAnnotationReader.java:42)
	at com.sun.xml.internal.bind.v2.model.impl.PropertyInfoImpl.isApplicable(PropertyInfoImpl.java:201)
	at com.sun.xml.internal.bind.v2.model.impl.PropertyInfoImpl.getApplicableAdapter(PropertyInfoImpl.java:212)
	at com.sun.xml.internal.bind.v2.model.impl.PropertyInfoImpl.<init>(PropertyInfoImpl.java:111)
	at com.sun.xml.internal.bind.v2.model.impl.ERPropertyInfoImpl.<init>(ERPropertyInfoImpl.java:42)
	at com.sun.xml.internal.bind.v2.model.impl.ElementPropertyInfoImpl.<init>(ElementPropertyInfoImpl.java:85)
	at com.sun.xml.internal.bind.v2.model.impl.RuntimeElementPropertyInfoImpl.<init>(RuntimeElementPropertyInfoImpl.java:48)
	at com.sun.xml.internal.bind.v2.model.impl.RuntimeClassInfoImpl.createElementProperty(RuntimeClassInfoImpl.java:160)
	at com.sun.xml.internal.bind.v2.model.impl.ClassInfoImpl.addProperty(ClassInfoImpl.java:867)
	at com.sun.xml.internal.bind.v2.model.impl.ClassInfoImpl.findFieldProperties(ClassInfoImpl.java:393)
	at com.sun.xml.internal.bind.v2.model.impl.ClassInfoImpl.getProperties(ClassInfoImpl.java:296)

**Comment by davidwatkins73** [comment]
I've, not seen this before.  However I did notice that we are building with Maven 3.5.x.  We have had some problems with earlier version of Maven, could you try a newer version ?

**Comment by ajaymohad123** [comment]
thanks Dave..

I still get the same error, have tried Maven 3.5.4 and Maven 3.6.0..any other suggestion please? do you want to see schema pom.xml?

**Comment by ajaymohad123** [comment]
Issue resolved.. had to delete .m2 directory/repo..

**Comment by davidwatkins73** [comment]
That's great news - not sure if we'd ever have remote-diagnosed that one!

Thanks for letting us know.
