### ISSUE TITLE
Logback - config file is not found when packaged in a jar

### ISSUE THREAD

**Issue by rovats** [khartec/waltz#3665]
Client deployment is as follows:

* Waltz war is deployed inside a Spring boot app (embedded tomcat instance)
* Spring boot app is packaged as a `jar` and deployed on OpenShift (Source to Image)
* `waltz-{local/dev/prod}.properties` and `waltz-logback.xml` are placed under the `resources` folder of the spring boot app
    * Waltz properties are read based on the environment (local/dev/prod) and added to the jndi environment of the embedded tomcat
    * `waltz-logback.xml` load fails because `LoggingUtilities` tries to read it as a file (and fails because it is in a jar)

The fix is to change the following snippet in `LoggingUtilities.configureLogging()`:

```` java
if (logbackConfigFile.exists()) {
    System.out.println("Found logback configuration file at: " + logbackConfigFile.getFile().getAbsolutePath());
                configurator.doConfigure(logbackConfigFile.getFile());
            } else {
                System.out.println("Logback configuration file not found..");
            }
````

to
```` java
    if (logbackConfigFile.exists()) {
                System.out.println("Found logback configuration file: " + logbackConfigFile);
                try (InputStream configInputStream = logbackConfigFile.getInputStream()) {
                    configurator.doConfigure(configInputStream);
                }
            } else {
                System.out.println("Logback configuration file not found..");
            }
````

**Comment by davidwatkins73** [comment]
Thanks for the detailed analysis!  Creating a PR for it now.
