### ISSUE TITLE
JobKey.ATTESTATION_CLEANUP_ORPHANS is never used

### ISSUE THREAD

**Issue by rovats** [khartec/waltz#3667]
Should probably be used in `ScheduledJobService.run()`

**Comment by rovats** [comment]
Ah ok, got it, but could be useful to do it optionally via a scheduled job too

**Comment by kamransaleem** [comment]
I think it we have soft delete enabled for the orphan cleanup the risk is reduced as it's easy to recover records

**Comment by rovats** [comment]
Yeah, not urgent though.. I'll ignore that job key for now and won't schedule it

**Comment by davidwatkins73** [comment]
Can this be closed or converted to a more actionable task ?

**Comment by davidwatkins73** [comment]
thx
