### ISSUE TITLE
Logical Data Elements: should be linked up to Data Types

### ISSUE THREAD

**Issue by rovats** [khartec/waltz#3673]
Currently, NWM are loading the logical data elements as part of the Data Types hierarchy, which makes it look messy.

The LDEs should ideally link up to Data Types and be displayed on the parent data type's page, showing links to physical specs using these.

**Comment by davidwatkins73** [comment]
These would presumably be a 'relates-to' (multiple) relationship rather than an 'owned-by' relationship.  Second is probably simpler but I suspect would not meet the requirement.

**Comment by rovats** [comment]
Relates-to probably makes more sense, as that would also allow for re-use of LDEs.
For eg: CounterParty_ID might be a field under multiple data types.

**Comment by davidwatkins73** [comment]
Had a quick chat with the people here who own this data.  They have a view that it's an 'owned-by' relationship from LDE to DT.  

The example you give on counterparty_id would be more like a enhanced type, an LDE would be more specific:  'bond-seller' is a 'counterparty-id' which belongs to the DT 'Party Data'

Not sure if that middle step (the type) is something we should look to add in the near future or omit for now.

**Comment by rovats** [comment]
Makes sense, I guess 'counterparty-id' is more of a physical field than logical.

I think LDEs owned by DTs is sufficient for now.

Will it be possible to plan this for 1.15? 
If there is bandwidth, the following would be great to get in 1.15 as a start (I can look to contribute from home if not):

* DDL change (parent data type on LDE)
* Display child LDE list on the parent data type page

**Comment by davidwatkins73** [comment]
Unlikely to make 1.15 from our side as we're about done for the year and we've got a few must-haves to work on in Jan which will take us up to the 1.15 release (est. late Jan).  

If you would like to take a stab at it please go ahead.  Happy to collaborate.  We will have to be careful not to bake in to many assumptions about the availability of the mappings to the DT's as we won't have them ready here.

**Comment by rovats** [comment]
`parent_data_type_id` will need to be a mandatory field on the `logical_data_element` I presume?

Should I populate it with -1 as default? 
And if an existing `unknown` data type exists, update all existing elements to be children of that type?

**Comment by kamransaleem** [comment]
In an ideal world yes. Can you populate with the unknown data type id as default?

**Comment by davidwatkins73** [comment]
We don't mandate an unknown data-type so it's not guaranteed to exist.  However a lot of our code does _expect_ it to exist so it may be worth attempting to guarantee it (via liquibase) and having dire warnings on startup if it does not exist.
