### ISSUE TITLE
Measurables: add unique composite index on category + external id

### ISSUE THREAD

**Issue by davidwatkins73** [khartec/waltz#3687]
@rovats  - any objections ?

**Comment by rovats** [comment]
No objections, makes sense. 

On 19 Dec 2018, at 20:29, David Watkins <notifications@github.com> wrote:

@rohit - any objections ?

**Comment by kamransaleem** [comment]
will look at this and try to ensure the same behaviour with MariaDB and PostgreSQL.

**Comment by kamransaleem** [comment]
Think we are ok for Postgres and Maria.

Postgres treats nulls as non equal: https://www.postgresql.org/docs/9.0/indexes-unique.html

Likewise for MariaDB: https://mariadb.com/kb/en/library/null-values/

Seems the only special treatment is for SQL Server 2008 onwards as per your comment above.
