### ISSUE TITLE
Physical Flow: soft code transport types into enum-value table

### ISSUE THREAD

**Issue by davidwatkins73** [khartec/waltz#3688]

**Comment by davidwatkins73** [comment]
Could be problematic as we currently have aliases defined against them which willl also need to become soft-coded.  Unfortunately we can't easily achieve this via `entity-alias` as it needs entities and enum values aren't entities (they have no identifying entity ref).  

Options:

**Abort**
Abort this change.

**Ignore aliases**
This would reduce the functionality of the  bulk importer 

**Hardcode aliases**
Makes this change a little redundant

**Add aliases in a single column on the `entity_enum` table**
Makes the task fairly simple but may be hidden gotchas and means we will always need a decoder to use properly

**Promote entity_enum to be a full entity**
This means adding a generated long PK.  Quite simple and would allow us to then use `entity_alias`

**Add a new table for `entity_enum_alias`**
Would look a bit like: `enum_kind | enum_value | alias`


Votes ?

**Comment by davidwatkins73** [comment]
We should probably go with the 'promote' option.  Probably the most work but may lead to a more generally useful way of interacting with enums.

**Comment by rovats** [comment]
Is the *promote* option to promote `enum_value` to a full entity? There seems to be a typo in the proposal.

My vote would be to add a new table `entity_enum_alias` and store the aliases there.

In my view, `entity_alias` is meant to store and *display* aliases (alternate names) for an entity, but `entity_enum_alias` will work the opposite way, it will be used to convert multiple aliases to a single enum value.

**Comment by davidwatkins73** [comment]
Good point happy to implement this way.  Anyone else got an opinion ?

**Comment by kamransaleem** [comment]
The case for a full entity ref would be to allow roll up by transport type for example, essentially following a similar approach to existing aggregations. Are we likely to need to do this?

**Comment by davidwatkins73** [comment]
Ok, will go with: **add `enum_value_alias` table**  alternative

**Comment by davidwatkins73** [comment]
![image](https://user-images.githubusercontent.com/576829/50467317-404e5600-099a-11e9-900c-05bb7c2cca43.png)

cascade delete from `entity_enum` to `entity_enum_alias`
