### ISSUE TITLE
Server Information: Hardware / Software end of life power symbol confuses users...

### ISSUE THREAD

**Issue by kamransaleem** [khartec/waltz#3694]

**Comment by davidwatkins73** [comment]
I think merging the 'flag' field and the 'on-date' fields would help:

![image](https://user-images.githubusercontent.com/576829/50373928-b8ed9500-05dd-11e9-82a4-453256e2fb6c.png)

**Comment by davidwatkins73** [comment]
![image](https://user-images.githubusercontent.com/576829/69490599-7c2bbd00-0e82-11ea-8144-0b6d87b79211.png)
