### ISSUE TITLE
Measurables: List page tallies ignore app entity lifecycle status

### ISSUE THREAD

**Issue by rovats** [khartec/waltz#3703]
Related to #1311

The tallies include inactive apps, but the measurable detail view excludes them, causing a mismatch.

**Comment by davidwatkins73** [comment]
Tagging with: **noteworthy** as will need to inform users that the numbers they see may change.

**Comment by rovats** [comment]
Also, there might be cases where we would want to include non-active apps on both the tallies and the detail view. That probably needs to be a setting on the measurable category.
Probably a new issue though.
