### ISSUE TITLE
Data type tree fails to render

### ISSUE THREAD

**Issue by rovats** [khartec/waltz#3716]
If a missing data type is being used to decorate a logical flow.

Console error:

````
TypeError: Cannot read property 'directCounts' of undefined
    at app~b995b8a7.da36da737c62a38787f6.js?ab9a4777f377cf809a27:1
    at Vt (vendors~app~7d359b94.9f4c7beec2ee46437158.js?ab9a4777f377cf809a27:9)
    at Function.qo (vendors~app~7d359b94.9f4c7beec2ee46437158.js?ab9a4777f377cf809a27:9)
    at vendors~app~7d359b94.9f4c7beec2ee46437158.js?ab9a4777f377cf8
````

Potential fix in `data-type-usage-count-tree.js` `prepareTree()` :

````
_.chain(usageCounts)
        .filter(uc => uc.decoratorEntityReference.kind === "DATA_TYPE")
//
// add another filter to check if dataTypesById[uc.decoratorEntityReference.id] exists
//
        .forEach(uc => {
            const dtId = uc.decoratorEntityReference.id;
            const dt = dataTypesById[dtId];
            const rag = ratingToRag(uc.rating);
            dt.directCounts = Object.assign(
                {},
                dt.directCounts,
                { [rag] : uc.count });
        })
        .value();
````

**Comment by davidwatkins73** [comment]
Additional thoughts:

- ensure these integrity failures are captured in the 'admin/orphan-entities' page
- could this be stopped on the server side via a simple join ?

**Comment by rovats** [comment]
Difficult to stop on the server side because the decorator entity kind could be anything (although we only use Data Types currently)

**Comment by davidwatkins73** [comment]
good point.  We've talked about reducing the decorator scope to just data_type decorators and then merging with the `physical_spec_data_type` table to create a generic `data_type_decorator` table.

Best course of action is probably to fix as you outlined above and create an issue for the consolidation as it is likely to be a reasonably large undertaking.
