### ISSUE TITLE
Server Information: add view page

### ISSUE THREAD

**Issue by davidwatkins73** [khartec/waltz#3735]
Initially needs to show:

- overview
- app associations
- bookmarks

**Comment by rovats** [comment]
Can we also show entity notes please?

Also, the loaders need to ensure `server_information.id` values remain consistent across loads (deleting and re-inserting records will change ids).

**Comment by davidwatkins73** [comment]
Will include entity notes.

**Comment by rovats** [comment]
There's also been a requirement discussed here to allow servers to be rated against measurables (once servers have their own dedicated views).
But the measurables code is hardcoded to use `EntityKind.APPLICATION`, so this will be a pretty big change.

**Comment by davidwatkins73** [comment]
May be worth a future change to move fully to dynamic sections rather than hardcoded sections.  Would be more consistent with the majority of the UI.....

**Comment by kamransaleem** [comment]
Agreed. It did cross my mind by I figured I would build out the page first and see what we end up with once it’s been matured a bit more with the other issues to build on this.
