### ISSUE TITLE
Server Information: view page should be linkable via hostname or external id

### ISSUE THREAD

**Issue by davidwatkins73** [khartec/waltz#3737]
e.g.    `/waltz/#/server/hostname/myhost.foo.baa.xyz`

**Comment by kamransaleem** [comment]
external id is done, will implement hostname with this issue

**Comment by davidwatkins73** [comment]
Will it allow for short hostnames as well as fqns ?

**Comment by kamransaleem** [comment]
the search feature supports this.  Is it reasonable to expect the short hostname without the fqns to be unique though?  My thoughts are that it's not...
