### ISSUE TITLE
Server Information: Add unique constraint

### ISSUE THREAD

**Issue by rovats** [khartec/waltz#3738]
Suggest adding a unique constraint on `hostname` + `asset_code`

**Comment by rovats** [comment]
Not sure if we should include `environment` too? 
Thoughts?

**Comment by davidwatkins73** [comment]
FYI: We may remodel how this works, splitting it out to a `server_information` and a `server_usage` (join) table.  See #3740 as the driving change

**Comment by kamransaleem** [comment]
see #3783
