### ISSUE TITLE
Database Information: Add unique constraint

### ISSUE THREAD

**Issue by rovats** [khartec/waltz#3739]
`asset_code` + `database_name` + `instance_name`

**Comment by rovats** [comment]
Not sure if we should include `environment` too? 
Thoughts?

**Comment by davidwatkins73** [comment]
FYI: We may remodel how this works, splitting it out to a `database_information` and a `database_usage` (join) table.  See #3740 as the driving change

**Comment by kamransaleem** [comment]
see #3784

**Comment by davidwatkins73** [comment]
@kamransaleem - I think this can be closed as it's no longer applicable?
