### ISSUE TITLE
Physical Flows: Document proposal to decorate flow with (optional) servers

### ISSUE THREAD

**Issue by davidwatkins73** [khartec/waltz#3740]
Need to think about how this interacts with:

- critical flows
- cloud computing (perhaps no servers - instead there may be a service name or similar)
- load balancers (i.e. api users of waltz in DB hit our apache l,oad balancer using it's DNS name, not the underlying hostname)

**Comment by kamransaleem** [comment]
Can servers, load balancers and even resource groups (in the context of cloud computing) be considered ‘components’ of an application after which a physical flow can be annotated with the components that facilitate it.
