### ISSUE TITLE
License: move to APL2 ?

### ISSUE THREAD

**Issue by davidwatkins73** [khartec/waltz#3744]
[Apache Public License 2](https://www.apache.org/licenses/LICENSE-2.0)

Investigate pros and cons.  

Probable pre-req if we want to transition project to FINOS.

**Comment by davidwatkins73** [comment]
@rovats could you check with your lot to see if they would be happy with this?

**Comment by davidwatkins73** [comment]
If we are doing this we should do it early in the 1.17 cycle

**Comment by rovats** [comment]
> @rovats could you check with your lot to see if they would be happy with this?

@davidwatkins73 no objections on this from here
