### ISSUE TITLE
Scenario Diagram: Add link to domain item on info pop-up

### ISSUE THREAD

**Issue by rovats** [khartec/waltz#3755]
To allow users to drill-down and view the domain item (eg: App view page):

![image](https://user-images.githubusercontent.com/15289335/51095585-d7f5d600-17db-11e9-94a0-fb9030251909.png)

**Comment by davidwatkins73** [comment]
It's a bit tricky as it's a pure svg/html popup and doesn't get rendered via angular, therefore we can't use an `sref`.  Will have a look to see what we can do.

**Comment by rovats** [comment]
Could we do something similar to the svg diagram block processors?

**Comment by davidwatkins73** [comment]
Don't think that would work as the block processors still execute in scope of a angular digest cycle.
