### ISSUE TITLE
Scenario Diagram: Adding an app fails

### ISSUE THREAD

**Issue by rovats** [khartec/waltz#3756]
URL being formed:
`/api/scenario/id/6/rating/17155/1520/1484/[object%20Object]`

The rating being sent is an object istead of a char.

Issue is possibly caused by this code in: `roadmap-scenario-diagram.js`:
````
const getLastOrDefaultRating = (app) => {
        const getDefaultRating = () => _.chain(vm.ratingsByCode)
            .values()
            .sortBy(["position"])
            .head()
            .value();
        return _.get(vm.lastRatings, [app.id], getDefaultRating())
    };
````

**Comment by davidwatkins73** [comment]
This also needs a fallback of 'last-resort' if the default rating cannot be found (and it's missing a semi-colon :) )
