### ISSUE TITLE
Surveys: survey_run.issued_on is null even when status is 'ISSUED'

### ISSUE THREAD

**Issue by davidwatkins73** [khartec/waltz#3759]
Not sure if this is a mistake in the GUI, it looks like the loaders for surveys set this field, but I can't see anywhere within the main codebase that does.

@kamransaleem , @rovats  - thoughts ?

**Comment by rovats** [comment]
It is set in 
`SurveyRunDao.issue()`, 
called from `SurveyRunService.updateSurveyRunStatus()` 
called from `survey-run-create.js -> onSaveRecipient()`

**Comment by davidwatkins73** [comment]
Thx, will need to dig deeper as a _lot_ of our issued surveys have a null `issued_on` date.

**Comment by rovats** [comment]
Not sure why, are they very old surveys (could have been a bug)? Or may be the ones created by the loader?
There are no `issued` surveys here with a null `issued_on` date.

**Comment by davidwatkins73** [comment]
Think this must be coming from the dataloaders - cannot reproduce or find any suspect code in Waltz.  RV: Thanks for checking.
