### ISSUE TITLE
Database: support an in memory database

### ISSUE THREAD

**Issue by davidwatkins73** [khartec/waltz#3778]
Will help with continuous builds and automated testing

**Comment by davidwatkins73** [comment]
Options:

- H2
- HSQLDB
- Apache Derby

**Comment by davidwatkins73** [comment]
jOOQ supports all three.

**Comment by rovats** [comment]
H2

**Comment by davidwatkins73** [comment]
Tend to agree - it seems to be the most active, plus I've used it before (but not with liquibase)

**Comment by davidwatkins73** [comment]
Ok, H2 kinda works okay.  One problem is that it tends to uppercase everything which breaks code where we do an explicit field grab (e.g. `table.field("id")` in the `EntityHierarchy` rebuild stuff).  Investigating to see if there is a way around it.

**Comment by rovats** [comment]
So, is it unable to find the fields if they are specified in lower case?

Could iterate over `table.fields()` and do a `equalsIgnoreCase()` on `field.getName()` to find the `id` and `parent_id` fields may be?

**Comment by davidwatkins73** [comment]
Y, I thought about that but discounted as it will be difficult to remember to do it any other time we do a dynamic field lookup.  Sure there must be a way to fix it.  There is a promising looking connection parameter: `DATABASE_TO_UPPER=false`, but it didn't seem to do anything when I tried it.  Will try again later today/this eve.

**Comment by davidwatkins73** [comment]
That parameter (`DATABASE_TO_UPPER`) does work.  It's now generating the schema with the correct casing.
