### ISSUE TITLE
Hierarchy rebuilds should be done in transactions

### ISSUE THREAD

**Issue by rovats** [khartec/waltz#3786]
If the rebuild errors, the current hierarchy data will be lost.

**Comment by rovats** [comment]
Happened here, the person hierarchy was deleted and the re-create errored, because of which people weren’t able to see their apps.

**Comment by davidwatkins73** [comment]
Figured that was what must have happened!

**Comment by rovats** [comment]
It was in prod, unfortunately.

**Comment by rovats** [comment]
We should also look at using `BatchProcessingCollector` when storing hierarchy records (at least for `Person` hierarchy, due to the large number of records to be saved)

**Comment by davidwatkins73** [comment]
y, kind of want to rewrite it so we can make it operate incrementally for intra-day updates.  Especially with the taxonomy editing stuff now in 1.15

**Comment by rovats** [comment]
If we do the delete and re-inserts in a transaction, I think we should be ok for intra-day rebuilds too, as the interim state will not be visible to the user.

And the measurable lists will never be that big. 
An separate optimisation for measurables could be to only rebuild for a specific category (after a manual edit)

**Comment by kamransaleem** [comment]
Would need to specify NOLOCK for reads whilst the updates are being done in a transaction.  SQL server, for example doesn't do this by default...

**Comment by rovats** [comment]
Not sure allowing reads of uncommitted data is a good idea though?
NOLOCK also has other issues I think, like returning the same row twice sometimes.

**Comment by davidwatkins73** [comment]
Going with the simplest fix at the moment (wrapping delete/insert with a tx).  

Lets see how that works out before trying anything with more complexity.
