### ISSUE TITLE
Server Information: Ability to associate a servers with physical flow

### ISSUE THREAD

**Issue by kamransaleem** [khartec/waltz#3803]
New table: `physical_flow_node`

| Column             | Type      | Mandatory | Description                                                   |
|:-------------------|:----------|:----------|:--------------------------------------------------------------|
| `physical_flow_id` | long      | **y**     | id of the physical flow                                                            |
| `side`             | enum      | **y**     | one of: `SOURCE` or `TARGET` to indicate the side of the flow |
| `node_entity_kind` | enum      | **y**     | flow node entity kind                                         |
| `node_entity_id`   | long      | **y**     | flow node entity id                                           |
| `description`      | string    | n         | a description of the nature of the participation of the node  |
| `last_updated_by`  | string    | **y**     | user id of last editor or creator if new                      |
| `last_updated_at`  | timestamp | **y**     | when this record was created                                  |
| `provenance`       | string    | **y**     | the provenance of the record                                  |

primary key on (`physical_flow_id`, `side`, `node_entity_kind`, `node_entity_id`)

**Comment by davidwatkins73** [comment]
Not sure about the table name. Agree with the proposed DDL though. Let's see if we can come up with a more descriptive name...
