### ISSUE TITLE
Server Information Stats: no longer de-duplicate on hostname

### ISSUE THREAD

**Issue by rovats** [khartec/waltz#3804]
`ServerInformationDao.calculateStatsForAppSelector()`, the earlier de-duplication logic (`group by` hostname) has been lost in the re-factor of the tables in v1.16

**Comment by rovats** [comment]
The rolled up stats will still need to de-duplicate on hostname.
For eg:

`Server 1` is used by two apps:
`App A`
`App B`

If you create an app group containing these two apps, `Server 1` should only be counted once, and not twice.

**Comment by davidwatkins73** [comment]
Moving to wip as I _think_ this has been resolved as part of #3850 amendment.  Will check tomorrow

**Comment by rovats** [comment]
@davidwatkins73 This still needs to be resolved I think (based on the code in the master branch), unless the de-duplication is happening somewhere other than the DAO.

Also, we'll need to look at `ServerInformationDao.calculateEnvironmentStats()` as well, as that could cause the rolled up pie charts to have different numbers compared with the OS/Location charts.

Eg: Server 1 is used by App A and App B, either in the same or different environments
The current query will count Server 1 twice in the environment tally.

I think even if a server is being used in different environments, we should only count the server once (and pick either the min or max environment).

**Comment by davidwatkins73** [comment]
@rovats - we want the environment chart to have potentially different numbers as it will reflect the fact that certain servers support more than one env.  The other stats de-dupe hosts.  

The gui now displays a note if the numbers don't match with a brief explanation:

![image](https://user-images.githubusercontent.com/576829/53962706-af0b0680-40e3-11e9-804e-789cdee096c3.png)
