### ISSUE TITLE
Measurable rating description: support markdown in description

### ISSUE THREAD

**Issue by rovats** [khartec/waltz#3808]
This was fixed in #2460, looks like a regression.

`measurable-rating-panel.html`

**Comment by davidwatkins73** [comment]
Fixing as part of #3734 .    Not sure if the above mentioned fix was related. Not sure if rating scheme items have ever been markdown aware.

**Comment by rovats** [comment]
Apologies, I had linked the wrong issue earlier, fixed now.
Markdown support was initially added by #2460
