### ISSUE TITLE
Facet: Explore approaches to simplifying  IdSelectionOptions and AppIdSelectionOptions

### ISSUE THREAD

**Issue by kamransaleem** [khartec/waltz#3818]
e.g.
`IdSelectionOptions<? extends Facets>` and do away with the `ApplicationIdSelectionOptions` extending `IdSelectionOptions`.

**Comment by kamransaleem** [comment]
#3810

**Comment by davidwatkins73** [comment]
Perhaps this could be implemented as a simple (maximal) property on `IdSelectionOptions` ?

```[java]
abstract class IdSelectionOptions {
  ....
  public abstract SelectionFilters selectionFilters();
 ....
}

abstract class SelectionFilters {
   @Value.Default
   public abstract Set<ApplicationKind> applicationKinds() { ... }
   ...
}
```

We lose some safety and have the risk of `SelectionFilters` becoming bloated.  But it minimizes code paths that need to do `instanceOf` and casting.
