### ISSUE TITLE
SVG Diagrams: reduce margins

### ISSUE THREAD

**Issue by rovats** [khartec/waltz#3842]
Currently the size calculation is, which leaves a lot of whitespace around diagrams, and renders diagrams with a lot of content unreadable:

```
function resize(elem, win) {
    const width = win.innerWidth * 0.7 || 1024;
    select(elem[0])
        .select("svg")
        .attr("width", `${width}px`)
        .attr("height", `${width*0.8}px`);
}
```

The following modification uses the available space more appropriately:
```
function resize(elem, win) {
    const width = win.innerWidth * 0.9 || 1024;
    select(elem[0])
        .select("svg")
        .attr("width", `${width}px`)
        .attr("height", `${width*0.9}px`);
}
```

If this doesn't work for all diagrams, we should probably make these params configurable in the database.

**Comment by davidwatkins73** [comment]
IIRC it was done this way because otherwise almost all our diagrams started to vertically scroll.  This is due to the majority of monitors now having ratios of 16:9 but diagrams tend to be produced in a form more suited to 'older' 5:4/16:10 ratios (squarer).

**Comment by rovats** [comment]
I see, probably best to make these percentages configurable for each diagram.
And if not set, we fall back to these current default values.
