### ISSUE TITLE
Server Information: migrate environment to server usage

### ISSUE THREAD

**Issue by davidwatkins73** [khartec/waltz#3850]
In a previous refactoring (#3783)  we have split `server_information` into `server_information` and `server_usage`.  The `environment` field remained in `server information`, however a lot of systems share servers across envs (especially DEV/UAT etc) and this results in data-loss/inaccuracies when the data is migrated. 

To remedy this we propose to move `environment` to `server_usage`.  **However** this will mean either going back over the changelog and amending previous changes or accepting the data-loss and relying on fresh imports to reset the system.  Note the split has not yet been released (due for 1.16), so no prod data should be at risk (unless you've deployed into prod directly from master)

@rovats - any opinion on this from your side ?

**Comment by rovats** [comment]
@davidwatkins73 this new change hasn't been deployed here yet to any environment, so no issues here.

Adding `environment` to `server_usage` makes sense.
`Server_Information` should only contain server level info (hostname/hardware etc)

**Comment by davidwatkins73** [comment]
Fixed in changelog.  If you _have_ applied the changes to a database this should get you back on track:

```sql
update databasechangelog set md5sum = null where id in ('20190124-3783-1', '20190124-3783-2', '20190124-3783-3');
alter table server_usage add column environment varchar(64);
```
