### ISSUE TITLE
DataType Page: View Page:  Sources and Sinks sections

### ISSUE THREAD

**Issue by davidwatkins73** [khartec/waltz#390]
Should include:

* Distirubtors,
* Consumers
* Originators should be flagged,
* Modifiers should be flagged
* Authoritativeness should be flagged (incl. for what OU)

Bonus points for showing authoriativeness of upstream downstreams for each app/OU combo

**Comment by kamransaleem** [comment]
Suggested queries for retrieving data for sources & sinks:


-- Applications that have an auth rating and the sink counts
select df.source_entity_id, sa.name, df.data_type, au.rating, au.parent_id, o.name, count(df.target_entity_id) as '#consuming apps'
--select *
from data_flow df
  inner join application a
    on a.id = df.target_entity_id
  inner join application sa
    on sa.id = df.source_entity_id
  inner join authoritative_source au
    on df.source_entity_id = au.application_id
       and df.data_type = au.data_type
       and au.parent_kind = 'ORG_UNIT'
  inner join entity_hierarchy eh
    on eh.ancestor_id = au.parent_id
       and eh.kind = 'ORG_UNIT'
       and eh.id = a.organisational_unit_id
  inner join organisational_unit o
    on o.id = au.parent_id
where df.source_entity_kind = 'APPLICATION'
      and df.target_entity_kind = 'APPLICATION'
      --and df.source_entity_id = 16185
      and df.data_type = 'TRANSACTION'
group by df.source_entity_id, sa.name, df.data_type, au.rating, au.parent_id, o.name

union

-- All Authoritative sources that don't have any consuming applications
select DISTINCT au.application_id, sa.name, au.data_type, au.rating, au.parent_id, o.name, 0 as '#consuming apps'
from authoritative_source au
  inner join application sa
    on sa.id = au.application_id
  inner join organisational_unit o
    on o.id = au.parent_id
where not exists(select *
                 from data_flow df
                   inner join entity_hierarchy eh
                     on eh.ancestor_id = au.parent_id
                        and eh.kind = 'ORG_UNIT'
                   inner join application a
                     on a.organisational_unit_id = eh.id
                        and df.target_entity_id = a.id
                 where  df.source_entity_id = au.application_id
                        and df.data_type = au.data_type)
      --and au.data_type = 'RISK'

union

-- All flows that source from an application that is not an authoritative source
select df.source_entity_id, a.name, df.data_type, 'UNKNOWN' as rating, a.organisational_unit_id, o.name, count(*) as '#consuming apps'
from data_flow df
  inner join application a
    on a.id = df.target_entity_id
  inner join entity_hierarchy eh
    on eh.id = a.organisational_unit_id
       and eh.kind = 'ORG_UNIT'
  inner join organisational_unit o
    on o.id = a.organisational_unit_id
where not exists(
    select *
    from authoritative_source
    where application_id = df.source_entity_id
          and parent_id = eh.ancestor_id
          and data_type = df.data_type
)
      and df.data_type = 'RISK'
group by df.source_entity_id, a.name, df.data_type, a.organisational_unit_id, o.name
