### ISSUE TITLE
Source Data Rating page doesn't load

### ISSUE THREAD

**Issue by kamransaleem** [khartec/waltz#3913]
```
Exception: No enum constant com.khartec.waltz.model.EntityKind.APP_RATING / java.lang.IllegalArgumentException
```

**Comment by davidwatkins73** [comment]
We can fix short term this by cleaning data I think.

**Comment by davidwatkins73** [comment]
This is caused by an incorrect Data Loader and is outside of Waltz control.  We _could_ make Waltz skip rows it doesn't understand but for now failing fast is possibly a better solution as this isn't a user error, rather it is an error made by the integrators.
