### ISSUE TITLE
Flow Diagram:  Thumbnail support (DDL)

### ISSUE THREAD

**Issue by kamransaleem** [khartec/waltz#3923]
1) Add database table: `entity_attachment`
```
id | entity_kind | entity_id | name | description | last_updated_at | last_updated_by | mime_type | attachment_kind | blob | provenance
```
Primary key on id.  Non unique index on `entity kind` and `entity_id`

Attachment Kind: `thumbnail | reference`

2) Immutable, DAO, Service and Endpoint `EntityAttachment`
- getById
- findByRef
- save, update
- delete

3) Create a .png file from an svg when a flow diagram is saved

4) Flow Diagram section to render thumbnails and use as a primary nav aid.  Include search and filter.  Potentially use [Isotope](https://isotope.metafizzy.co/) for thumbnail rendering and filtering.

**Comment by davidwatkins73** [comment]
I think a table dedicated to thumbnails will keep things simple.  Each entity can have zero or one thumbnails (no need to support collections).  waltz-entity-link could speculatively have a look to see if it can render a popover!

name | desc 
--- | --- 
entity_kind |  
entity_id |
last_updated_at |
last_updated_by | 
mime_type | needed so client can render correctly
blob |
external_id | _just in case!_
provenance |

**Comment by davidwatkins73** [comment]
Do you want to leave this open or close and create a new issue to finish it off ?
