### ISSUE TITLE
Authentication: support external authentication

### ISSUE THREAD

**Issue by rovats** [khartec/waltz#3930]
A simple approach could be:

* Setting to provide a REST endpoint for authentication
* If set, username and password entered by the user is passed to the endpoint, and a response map is expected:
  * `success`: boolean
  * `waltzUserName`: String (this is useful since the external authentication might not use emails, eg: LDAP might have a different user name than email, but email can be fetched from LDAP)
  * `errorMessage`: String
* `AuthenticationEndPoint` calls this external endpoint, and creates the JWT token as normal, once the user is authenticated

**Comment by rovats** [comment]
Just implemented this, works very well. The authentication is delegated to an external end point which in turn authenticates against LDAP, and sends back the auth result and user email (LDAP usernames are different to emails here).

Will contribute the complete code when I can.

```
private AuthenticationResponse authenticate(LoginRequest loginRequest) {
        return settingsService
                .getValue(NamedSettings.externalAuthenticationEndpointUrl)
                .map(url -> doExternalAuth(loginRequest, url))
                .orElseGet(() -> doInternalAuth(loginRequest));
    }
```

**Comment by davidwatkins73** [comment]
Sounds great. Look forward to seeing the pull request!
