### ISSUE TITLE
Admin screen: view rating schemes

### ISSUE THREAD

**Issue by davidwatkins73** [khartec/waltz#3934]
a) Figure out how to add a page to the admin screen (routes.js etc)
b) Create page
c) in controller do service broker call to retrieve all schemes (steal from roadmap config section)
d) ng-repeat over schemes.   ng-click on scheme to show assoc. rating items.

**Comment by santoshyadav198613** [comment]
Hi @davidwatkins73 ,
Can i take this task.

**Comment by davidwatkins73** [comment]
Yes, please do!
Starting points:
- `waltz-ng/client/system`  (most admin ui stuff is in here)
  - `./routes.js` - register a view and url matcher
  - `./rating-scheme-view.html` - view display template
  - `./rating-scheme-view.js` - the view controller
    - inject `ServiceBroker` into the controller to access the back end
    - obtain the schemes like `serviceBroker.loadViewData(CORE_API.RatingSchemeStore.findAll).then(r => vm.foo = r.data)`
       - using service broker in this way rather than going directly to the stores let's us determine if we want to do page or session level caching.  Less important for this page but very important on the bigger pages.


Hope this helps get you started.  Feel free to fire away with questions.

**Comment by davidwatkins73** [comment]
Oh, you may want to take a look at the `rating-scheme-legend.js` component for an example of how to display a scheme.  

Note we register components with a prepended `waltz`, so in html it would be `<waltz-rating-scheme-legend foo='baa'>...`

**Comment by santoshyadav198613** [comment]
Hi @davidwatkins73 ,
i have completed the setup, but getting below error when trying to update the project using maven:

Cannot infer type argument(s) for <U> map(Function<? super T,? extends U>)

Any idea.

Regards,
Santosh

**Comment by santoshyadav198613** [comment]
Also can you guide me setup page for API, i was able to run the UI applicatio, but getting failed as the APIs are not up and running, may be i am not referring to correct page for project setup

**Comment by davidwatkins73** [comment]
Hi, could you attach the maven entire maven output to help us diagnose the issue.  The backend can be started in several ways.  In dev we typically launch the `com.khartec.waltz.web.Main` application to provide the java based backend and run `npm run dev-server` to provide the frontend.  Running the UI in this mode switches the angular client to use `localhost:8443` as a backend base url.  (see `waltz-ng\client\networking.js` for impl).
