### ISSUE TITLE
Application: should be apparent on an app which Roadmaps it has been referenced in

### ISSUE THREAD

**Issue by kamransaleem** [khartec/waltz#3957]

**Comment by davidwatkins73** [comment]
How did you envisage this to work?  We already have the roadmaps sub-section in the ratings section.... 

![image](https://user-images.githubusercontent.com/576829/57679512-6b70d380-7623-11e9-87af-7abd22a1dc00.png)

**Comment by kamransaleem** [comment]
Apologies, I must have missed this.  Will close this issue

**Comment by davidwatkins73** [comment]
Ok, was just wondering if you thought we should have done an appgroup type thing.
