### ISSUE TITLE
App Ratings Section: pop-over should support markdown

### ISSUE THREAD

**Issue by rovats** [khartec/waltz#4074]
User entered comments can contain markdown formatted text.

**Comment by davidwatkins73** [comment]
Oddly enough just came out of a meeting where we discussed the need for this.

**Comment by davidwatkins73** [comment]
We also need to consistently refer to this field as comment (it's description in the editor).

**Comment by davidwatkins73** [comment]
Also need to ensure it appears in the exports (alloc and ratings) with the correct name
