### ISSUE TITLE
Add new field: Lifecycle_Status to Server_information and db_info table

### ISSUE THREAD

**Issue by rovats** [khartec/waltz#411]
The status can be 'Active', 'New', 'Unallocated', 'Unused', 'Retiring' etc (need to come up with a list).

We can then show a breakdown based on this field in the technology section.

**Comment by davidwatkins73** [comment]
Would this be for the server or the OS installed on that server ?

**Comment by rovats** [comment]
This one would be for the server itself, but yes, we could potentially have one for the OS as well..

**Comment by rovats** [comment]
List of potential statuses:

Active
Planned
Retiring
Unused
Unallocated
New
Build
Retired
Temp Power off
Removed

**Comment by davidwatkins73** [comment]
Can we whittle this down a bit ?   Would have a hard time differentiating between these states

**Comment by davidwatkins73** [comment]
````
Building
  |
Active     =  Inactive
  |
Retiring
 |
<deleted>
````
