### ISSUE TITLE
Group Views: links from summary widgets no longer work

### ISSUE THREAD

**Issue by rovats** [khartec/waltz#4117]
Broken hyperlinks on widgets like *App by Investment Status*, *Complexity*, *Servers* etc on grouped views.

Probably broken since we moved to dynamic sections. 

![image](https://user-images.githubusercontent.com/15289335/58860993-03b22380-86cb-11e9-912a-1904381a7e80.png)

**Comment by davidwatkins73** [comment]
Jess, I think this one should be much simpler now that #4138 is completed.  Inject the `DynamicSectionManager` and simply `activate(..)` the appropriate section.
