### ISSUE TITLE
UI: Key person sub-section

### ISSUE THREAD

**Issue by davidwatkins73** [khartec/waltz#4128]
Idea is to have a widget defined which given an entity kind will try and show a list of people with a certain involvement type. e.g.

```
kind = CI  ==> ["CI Sponsor", "CI Director"]
````
Clicking the widget should open the full 'person' section.  Involvement kind to entity kind relationships will need to be database driven as will be customer specific.

**Comment by davidwatkins73** [comment]
Something like:

`<waltz-key-people-sub-section parent-entity-ref='someRef'></...>`

Use the kind of `someRef` to determine a list of key roles and brings back the relevant people associated with `someRef`

**Comment by rovats** [comment]
+1 this will be useful

**Comment by davidwatkins73** [comment]
Available for:
- `APPLICATION`
- `CHANGE_INITIATIVE`

Configured using the `key_involvement_kind` table which links an involvement kind (id) to an entity kind.
