### ISSUE TITLE
Errors on scenario view after upgrading to v1.17.1

### ISSUE THREAD

**Issue by rovats** [khartec/waltz#4154]
Getting the following errors on scenario views after upgrading to v1.17.1, and the roadmap diagrams are not rendered correctly (columns and rows squashed together):
![image](https://user-images.githubusercontent.com/15289335/59657038-17768300-91bd-11e9-8ff3-2d058e57b926.png)

![image](https://user-images.githubusercontent.com/15289335/59657243-bb602e80-91bd-11e9-978c-e878ba3ffd00.png)

Potentially related to #4039 ?

**Comment by davidwatkins73** [comment]
Seems to be related to the number of cols, will look into it.

**Comment by davidwatkins73** [comment]
Patched in master, can you give it a spin.  Fix was v. small, I had forgotten to take into account the case when the number of columns was larger than 8 and we were `floor`ing the value down to zero, hence the squished rendering

**Comment by rovats** [comment]
Thanks @davidwatkins73 , that has fixed the issue.
