### ISSUE TITLE
Support for licence as an entity in Waltz

### ISSUE THREAD

**Issue by kamransaleem** [khartec/waltz#4174]
Table definition:

```
id | name | description | external_id | created_by / at | last_updated_by / at | provenance
```

Page to view licence definition, which should also include an `approval status` assessment.  Bookmarks to be able to reference a destination URL.  Also, include the ability to associate applications with licences.

**Comment by davidwatkins73** [comment]
Perhaps add people ?  Then we can add the licence approvers as a role.

**Comment by davidwatkins73** [comment]
Thinking about approval status - perhaps this should be a first class thing.  Then we can do some native Waltz stuff rather than dataloader.....

**Comment by rovats** [comment]
Is this to represent software licences? Vendor contracts?
Should we also store other information like: vendor, start date/ end date, cost, licence type, status, duration etc?

We've modeled contracts as a measurable here, with people association, entity notes for additional fields.

**Comment by davidwatkins73** [comment]
Interesting approach to use measurables.  We were thinking that the licenses should be simply things like GPL-v2, GPL-v3, EPL, BSD etc.  These may have an overall approval status, something like: `PENDING_APPROVAL|APPROVED|REJECTED|REQUIRES_EXCEPTION`.  

For things like start/end date, cost, duration - I think these belong on some kind of License usage entity.  But we aren't proposing to do much more than `license <-> app` in this issue.
