### ISSUE TITLE
Stats: When there are multiple outcomes, the stat name should only be displayed once on the entity view

### ISSUE THREAD

**Issue by rovats** [khartec/waltz#420]
Eg: if a stat has multiple outcomes marked as current, then on the entity (app) view they will be displayed as:

Stat Name | Outcome | Reason
----------- | ------------ | ---------
xyz | Yes | Pass
abc | Good | 2 of 5 values good
abc  | Bad | 3 of 5 values bad

but this would probably be better:

Stat Name | Outcome | Reason
----------- | ------------ | ---------
xyz | Yes | Pass
abc | Good | 2 of 5 values good
| | Bad | 3 of 5 values bad

**Comment by davidwatkins73** [comment]
do you mean like tags ?

**Comment by rovats** [comment]
Like a table, I have formatted the description to reflect this.

Also, for SUM_BY_VALUE stats, we might also want to display the underlying value, although if the value is always included in the **reason** (as above) then, we probably don't need to.
