### ISSUE TITLE
Assessments: Collapse down 'Not Provided' into a shortened list

### ISSUE THREAD

**Issue by kamransaleem** [khartec/waltz#4205]

**Comment by davidwatkins73** [comment]
This issue is an attempt to manage the rapid proliferation of assessments associated to entities.  Instead of showing all assessments, only those with a provided value will be shown in full.  Those without a provided value will be shown in a in-line muted section.

**Comment by davidwatkins73** [comment]
Before:
![image](https://user-images.githubusercontent.com/576829/61582139-d4dafa00-ab1e-11e9-88bf-da446eaa1c77.png)

**Comment by davidwatkins73** [comment]
![image](https://user-images.githubusercontent.com/576829/61583312-571eea80-ab2e-11e9-8d6f-b6623256020c.png)

Also included a read-only indicator.
