### ISSUE TITLE
Application -> Technology -> Server view updates

### ISSUE THREAD

**Issue by rovats** [khartec/waltz#421]
* New columns: **os_end_of_life_date** and **hw_end_of_life_date** on **server_information** table
* Two new pie chart showing breakdown based on OS EOL and HW EOL
* Grid view to show underlying server information (including Is End of Life column)

**Comment by davidwatkins73** [comment]
Guessing both of these are nullable.  Not sure if the grid view would show these by default.  Perhaps we should look at some icons to indicate differing conditions (near EoL, past EoL, etc)....

**Comment by rovats** [comment]
This issue can be closed, all the work required for it has been covered by other issues.
