### ISSUE TITLE
Long user-agent values cause SQL errors

### ISSUE THREAD

**Issue by rovats** [khartec/waltz#4210]
Insert into `user-agent-info` fails, and logs are filled with stack traces.

Suggest that we truncate the `user-agent` value before inserting into the DB or increase the field length.

Example value from IE (170 characters):

`Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET4.0C; .NET4.0E; Zoom 3.6.0)`

**Comment by davidwatkins73** [comment]
Will update the field size as impact is low and truncation will make parsing logs trickier for people.

**Comment by davidwatkins73** [comment]
Field increased to `VARCHAR(500)`
