### ISSUE TITLE
Application -> Technology -> Database view

### ISSUE THREAD

**Issue by rovats** [khartec/waltz#422]
* May be rename **database** table to **database_information**
* New column **end_of_life_date** (nullable) on **database** table
* New column **asset_code** on **database** table
* New column **lifecycle_status** on **database** table
* Pie charts
* Underlying grid view (including Is End of Life column)

**Comment by davidwatkins73** [comment]
good idea on the rename.  

re: EoL, see my comment in #421

**Comment by davidwatkins73** [comment]
Not adding lifecycle_status, will be part of #411

**Comment by rovats** [comment]
This issue can be closed, all the work required for it has been covered by other issues.
