### ISSUE TITLE
Surveys: remove status EXPIRED

### ISSUE THREAD

**Issue by davidwatkins73** [khartec/waltz#4223]
Can't see any usage of it in the database/loaders/survey actions.  Some `countBy` stuff for showing it, but nothing ever sets it.....

@rovats - thoughts?

**Comment by rovats** [comment]
It was created with the intention of marking survey instances as expired if they weren't filled in by their due date, but the idea was later dropped.

The status can be removed, if it is not used and there are no existing instances marked as Expired.
