### ISSUE TITLE
App Group: add an org unit to an application group

### ISSUE THREAD

**Issue by mitranc** [khartec/waltz#4251]
Add an org unit to an app group
use a widget similar to add app
entry should end-up in app_group_ou_entry table
existing component for selecting the org unit should be used for the interactive selection logic

Testing steps
Add / Remove the Organization Unit to a group and verify that correct applications are shown after refreshing the app-group screen for the affected application group.

**Comment by davidwatkins73** [comment]
Relates to #4228
