### ISSUE TITLE
Surveys: cannot submit as Person object is trying to deserialize derived field `name`

### ISSUE THREAD

**Issue by davidwatkins73** [khartec/waltz#4273]

**Comment by rovats** [comment]
Does this affect v1.18?

**Comment by davidwatkins73** [comment]
yes it does.  We have an upcoming 1.18.1 release on Weds which should fix this and a couple of others.

**Comment by rovats** [comment]
OK, thanks

**Comment by davidwatkins73** [comment]
Fixed, just waiting for it to go through IP review
