### ISSUE TITLE
Measurable Ratings: display rating_scheme_item descriptions

### ISSUE THREAD

**Issue by rovats** [khartec/waltz#4293]
This will help users understand complex rating schemes.

**On the measurable view** (may be add a rating scheme widget on the summary section?):

![image](https://user-images.githubusercontent.com/15289335/63320231-b7c26280-c33a-11e9-8c87-c7a9883d6224.png)

**On the app rating section**:

![image](https://user-images.githubusercontent.com/15289335/63320331-1982cc80-c33b-11e9-8296-4895c7f1ace2.png)

**Comment by davidwatkins73** [comment]
Sounds good, are you planning on the impl ?

**Comment by rovats** [comment]
Not currently planned Dave, may be in a future sprint.

**Comment by davidwatkins73** [comment]
![image](https://user-images.githubusercontent.com/576829/64494265-97732d00-d282-11e9-9084-37348719cade.png)
