### ISSUE TITLE
Represent event definition/last occurrence with associated entities in Waltz 

### ISSUE THREAD

**Issue by muzammil-ali1** [khartec/waltz#4294]

**Comment by davidwatkins73** [comment]
When you say events are you talking about __signals__ or __event definitions__ ?

Could you fill in a bit more detail about what this issue will comprise of please ?

**Comment by kamransaleem** [comment]
An event is defined as two parts, the actual details/meta about the event, i.e. the **definition**, the second part is essentially _when_ the event has occurred and which (if any) entities are associated to that **occurrence**.

**Database definitions**

**_event_definition_**: 
```
id | external_id | name | desc | owning_entity | created_at/by | last_updated_at/by | provenance
```

**_event_occurrence_**: 
```
id | external_id | definition_id | associated_entity | created_at/by | last_observed_at | provenance
```

_Open questions_
1. Can the above two tables condense into a single table and denormalise
2. Should user be able to create events via the Waltz UI or should these tables rely on being fed data
3. Should there be an event definition page or do we keeps events as a secondary entity, viewable only in the context of the associated entity

**Comment by muzammil-ali1** [comment]
Proposed UI changes:
Display last_observed_at with each associated entity.

Questions:
1. Wouldn't it better to keep last_observed_at on the definition level as there will be one (latest) signal per definition but can be many associated entities.
2. In the event_occurrence table if we use definition_id as foreign key do we need external_id.

**Comment by kamransaleem** [comment]
makes sense.
