### ISSUE TITLE
Create an oprhan entity view

### ISSUE THREAD

**Issue by rovats** [khartec/waltz#443]
Will track orphan:

1) Apps
2) End user apps
3) Capabilities
4) Org units?
5) Auth sources - missing apps

**Comment by davidwatkins73** [comment]
Current fix adds view to identify roots - think we still need a view similar to:

'Apps which belong to a non-existent OU'
'App-Capability records which don't point to existent caps/apps'
'Authsources pointing at non-existent OU/Apps'

etc
