### ISSUE TITLE
Entity Tags: convert tag as waltz entity

### ISSUE THREAD

**Issue by muzammil-ali1** [khartec/waltz#4469]
- split the current entity_tag table into following table.

- Tag [id, name, owner_entity_kind, created_by, created_at, provenance]
- Tag_involvement [tag_id, entity_id, entity_kind, created_at, created_by, provenance]

update the existing tag functionality to use new tables and delete old one.

**Comment by davidwatkins73** [comment]
**Tag**

name|type
---|---
id | auto-inc
name|tag name
target_kind| entity kind enum

**Entity_tag**

name|type
---|---
tag_id|fk -> tag.id
entity_id| -
entity_kind | -
provenance | string
created_by | string
created_at | string
