### ISSUE TITLE
Software Package: Improved support for usages, versions and licences

### ISSUE THREAD

**Issue by kamransaleem** [khartec/waltz#4496]
### Software Package
A represenation of a software package / library

Name            |       Type            | Description
---             | ---                   | ---
Id              | Long                  | Sequential identifier
Group           | String                | A group or namespace for this package, could double up as the publisher
Name            | String                | Name of the package
Description     | String                | Description
External Id     | String                | External identifier based on source of package
Created At      | Timestamp             | -
Created By      | User Id               | -
Provenance      | String                | Where this data point came from

### Software Package Version
A listing of the licences for the software version. 

Name                 |       Type            | Description
---                  | ---                   | ---
Id                   | Long                  | Sequential identifier
Software Package Id  | Long                  | FK to Software Package
Version?              | String                | Version of the package (nullable to represent the unknown)
Description          | String                | Description
External Id          | String                | External identifier
Created At           | Timestamp             | -
Created By           | User Id               | -
Provenance           | String                | Where this data point came from

### Software Package Usage
An application's usage of a software package is version specific, hence will link to this record.

Name                 |       Type            | Description
---                  | ---                   | ---
Id                   | Long                  | Sequential identifier
Application Id       | Long                  | FK to Application
Software Version Id  | Long                  | FK to Software Package version (a usage will always be for a specific version)
Created At           | Timestamp             | -
Created By           | User Id               | -
Provenance           | String                | Where this data point came from

### Software Package Version Licence
A software package usually has a version, 

Name                 |       Type            | Description
---                  | ---                   | ---
Id                   | Long                  | Sequential identifier
Software Version Id  | Long                  | FK to Software Package version (a licence will always be for a specific version)
Licence Id           | Long                  | FK to Licence
Created At           | Timestamp             | -
Created By           | User Id               | -
Provenance           | String                | Where this data point came from

**Comment by davidwatkins73** [comment]
Given the high rate of expected 'unknown' versions should we be explicit and have an `unknown_version` column, or are we being implicit and having usage which links to a version with a `null` value in `version`.

Also think the _software package version license_ table may have missed a vital FK :)

**Comment by kamransaleem** [comment]
updated, thanks
