### ISSUE TITLE
Nav aids: allow SVG export (download)

### ISSUE THREAD

**Issue by rovats** [khartec/waltz#4568]
With links to Waltz entities ideally.

**Comment by rovats** [comment]
Thinking of including this in the `Extractor` framework, which handles Excel\CSV currently.

Any thoughts?

**Comment by davidwatkins73** [comment]
Sounds like a good idea. Recently made the extractors a bit more generic
and less Excel specific. Feel free to further refactor.

**Comment by rovats** [comment]
Cool, shouldn't need to much refactoring, just an overloaded `writeExtract` which takes in `data` instead of a `Select<?>`.

The interesting bit will be injecting hyperlinks to Waltz entities in the SVG.
