### ISSUE TITLE
Involvement: add read-only flag

### ISSUE THREAD

**Issue by davidwatkins73** [khartec/waltz#4626]
The read-only aspect of involvement records is currently implicit (based on the provenance being != 'waltz').  This isn't working out so well in practice so we want to move this to be more explicit.

Note: Any migration script should honour the above implicit rule.

**Comment by davidwatkins73** [comment]
Marking this as small change as it is hopefully low complexity.  However it does touch all layers in waltz and is a good candidate for using as a teaching exercise.

**Comment by kearash1** [comment]
In summary we want to stop using the provenance check and start using an explict check against a readonly flag.


Steps:
- Server side
  - Add column via a liquibase change.  Column should be called `is_read_only` and defaults to `false`
    - look in `changelog...xml` files for examples
  - Write a liquibase update change to set the `is_read_only` flag dependent on `provenance <> 'waltz'`
  - find the involvement model and dao and ensure field is created in the model and populated in the dao.
  - in service reject modifications if `is_read_only` flag is set



- Client Side
  - Add little lock icon to visually indicate a read only record
    - add a popver to explain what the icon means
  - show/hide remove button based on this flag (i..e don't use the provenance check)

Update any internal data loaders to populate the flag correctly.
