### ISSUE TITLE
Data flows should allow a verb per data-type e.g. create, update, read, distribute

### ISSUE THREAD

**Issue by mcneilm** [khartec/waltz#50]

**Comment by davidwatkins73** [comment]
To check my understanding, let me take an example logical flow:

    App A --[transaction data]--> App B

The RHS (appB) would almost always view this as a read
The LHS (appA) could view this as create/update/distribute - but not as read.

In some ways update / distribute could be validated as those verbs would imply that an incoming feed of that type exists. If an incoming feed did not exist then it would be impossible to update or distribute that data type......

**Comment by davidwatkins73** [comment]
Believe this can be closed as addressed via application data type usages.
