### ISSUE TITLE
Add EOL Status pie charts

### ISSUE THREAD

**Issue by rovats** [khartec/waltz#518]
* Server (Operating System and Hardware)
** Application Page
** Rollups (org unit etc)

* Database
** Application Page

**Comment by davidwatkins73** [comment]
![image](https://cloud.githubusercontent.com/assets/576829/18607966/d2977a9c-7cd3-11e6-8496-99c91926a31c.png)

**Comment by davidwatkins73** [comment]
just adding screenshots (for use in the release notes)
