### ISSUE TITLE
need to have a "view full hierarchy" feature for all sections

### ISSUE THREAD

**Issue by mcneilm** [khartec/waltz#52]

**Comment by davidwatkins73** [comment]
Does this refer to the org-unit home page ?  It currently only supports a diagram upload and a search feature.  

One of the OU structures I'm dealing with has > 5K nodes at ~ 11 levels of depth so a plain rendering didn't work out very well.  Perhaps an expandable tree (pre expanded to depth 'x') would be a suitable compromise for large trees ?

**Comment by davidwatkins73** [comment]
Further thinking, this may also mean filling in all parents / children when viewing a child item.  i.e. within a capability the hierarchy display components (above and below the overview box) only go one level in each direction.

Something like this ?

````
Capability: Operations > Confirmations
 
|-----------------------------------|
| Dispute Management                |
| ......                            |
|-----------------------------------|

  * Dispute Notification
     * Dispute Resolution
  * Something else
     * child of something else
