### ISSUE TITLE
Integrate multi select tree control into data-flow data type selection

### ISSUE THREAD

**Issue by kamransaleem** [khartec/waltz#534]

**Comment by davidwatkins73** [comment]
![image](https://cloud.githubusercontent.com/assets/576829/18607953/7ae1dd56-7cd3-11e6-9ba7-12da5bf106bb.png)

**Comment by kamransaleem** [comment]
Is something wrong with it?

**Comment by davidwatkins73** [comment]
Nope - just adding screenshots (for use in the release notes)

**Comment by kamransaleem** [comment]
Good idea
