### ISSUE TITLE
App Group: Bulk adding of applications into an App Group

### ISSUE THREAD

**Issue by kamransaleem** [khartec/waltz#703]

**Comment by davidwatkins73** [comment]
What's the use case for this - bulk adding via file or some other mechanism ?

**Comment by kamransaleem** [comment]
Just a list of asset codes in a text area separated by commas would suffice
I would guess.  Ash was the requestor so will follow up in the AM.

**Comment by davidwatkins73** [comment]
Ok - just want a bit of detail so we don't forget what this is about ;)

**Comment by davidwatkins73** [comment]
Perhaps split into create a 'mass selection' widget  (cut n' paste a list of names/codes/ids) and it presents a table with it's best guesses.  Clicking okay will then return the appropriate entity refs.  The output from this widget will feed the batch reg function.

**Comment by kamransaleem** [comment]
@kamransaleem
