### ISSUE TITLE
Entity name provider service

### ISSUE THREAD

**Issue by rovats** [khartec/waltz#795]
DAO and Service?

* Given an `EntityReference`, return the entity name
* Given a list of `EntityKinds` with `ID` and `Kind` jOOQ fields (aliased), return a `case` statement  to select the name, which will work something like this:

```
select *,
  case 
  when eh.kind = 'ORG_UNIT'
    then (select name from organisational_unit where id = eh.id)
  when eh.kind = 'ENTITY_STATISTIC'
    then (select name from entity_statistic_definition where id = eh.id)
  end as 'name'
from entity_hierarchy eh
where kind in ('ORG_UNIT', 'ENTITY_STATISTIC')
```

**Comment by davidwatkins73** [comment]
whats entity_hierarchy got to do with it ?

**Comment by rovats** [comment]
Nothing, just used it to demonstrate the `case` statement..

**Comment by rovats** [comment]
In this example, the calling code would send in `eh.kind` and `eh.id` to the name provider service and would get a `case` statement field back:

```
case 
  when eh.kind = 'ORG_UNIT'
    then (select name from organisational_unit where id = eh.id)
  when eh.kind = 'ENTITY_STATISTIC'
    then (select name from entity_statistic_definition where id = eh.id)
  end
```

The calling code can then use the case statement field in a query to fetch names in a single query.

**Comment by davidwatkins73** [comment]
How will this approach work for multiple entries which is the most common case (no pun intended) ?

**Comment by rovats** [comment]
The `select` statements inside the `case` refer to the `kind` and `id` fields of the outer query, so are co-related. That's why the calling code would need to pass in these two fields.

If you run the query against `EntityHierarchy`, you will get names for each record automagically.

**Comment by davidwatkins73** [comment]
why not something like (pseudo):

```
select name, id, 'APPLICATION' from application where id in (:appIds)
union
select name, id, 'ACTOR' from actor where id in (:actorIds)
```

where we optionally render union clauses depending on the kinds of the set of entity refs we wish to enrich ?

**Comment by rovats** [comment]
Could potentially blow up the `in` clause limit?

Also, this would need to be executed separately from the main query, after the entity-refs have been extracted, right? And then we'll have to set the names in the entity refs?

**Comment by davidwatkins73** [comment]
Ah, I think I get what you're trying to do.  I was thinking this was going to be an separate query as you just described.  Won't this approach perform v. badly ?

**Comment by rovats** [comment]
Potentially performance will take a hit, but I thought it shouldn't be worse than fetching the `EntityRefs` first and then querying for each one's name individually.

I plan to do some testing to figure out which approach performs better, but certainly using a `case` statement in the main query will be a lot more convenient, I think.

**Comment by rovats** [comment]
AVG times fetching 405,121 Entity Stat Value records with/without entity names: 

Without (all fields): 6500
With (all fields + entity name - using case): 7986
With (all fields + entity name - fetched one by one): 110989

**Comment by rovats** [comment]
@davidwatkins73 do you think we need a DAO and a Service for this? I am just thinking of putting this in the Service layer, since there is no underlying single table?

**Comment by davidwatkins73** [comment]
one by one ?  I thought option 2 was something more like:

````
namelessResults = dao.doQuery(x,y)
refsToResolve = flatmap(namelessResults, d -> extractRef(d))  // one or more refs that need names
resolvedRefs = resolveNames(refsToResolve)
namedResults = map(namelessResults, d-> enrich(d, resolvedRefs))
````

where `resolveNames` is like:

````
resolveNames(refs) {
     refsByKind = groupBy(refs, 'kind', r -> r.id);   // kind -> [ id... ]
     q = buildQuery(refsByKind)
     return q.fetch(TO_REF_MAPPER)
}
````

...and `buildQuery` looks something like:

````
buildQuery(refsByKind) {
   return refsByKind
        .map((k, ids) -> {
                 return dsl
                        .select(lookupNameField(k), lookupIdField(k), value(k.name))
                        .from(lookupTable(k))
                       .where(lookupIdField(k).in(ids));
         })
        .reduce(
               (acc, frag) -> acc.union(frag), 
                notSureTheBaseAccumulatorIs! )
````


Having typed all that I'm not sure how easy it will be to implement.  But it should be quick as it will generate a fairly simple statement to get arbitrary collections of names.

Thoughts ?

**Comment by rovats** [comment]
Yeah, shouldn't be too difficult to implement.. but having arbitrary number of ids in an `in` clause sounds dangerous, plus the complexity of first extracting the refs and then enriching them again with names.

I can give it a quick try to find out some numbers, but I don't suppose this can be that much quicker than the `case` statement.

**Comment by davidwatkins73** [comment]
yeah you're probably right.   The times with CASE where better than I expected.

**Comment by rovats** [comment]
Yeah `case` timings are good almost surprisingly..

So, Service + DAO or just Service?

**Comment by davidwatkins73** [comment]
Isn't it more like a utilities thing as it's making a fragment of a statement.  A bit like the idSelectorFactories ?

**Comment by rovats** [comment]
I've also got a method that fetches the name given a ref, but I guess that is not really required at this stage:

`public Optional<String> findEntityName(EntityReference ref) {`

**Comment by davidwatkins73** [comment]
Needs javadoc
