### ISSUE TITLE
Convert capabilities table to include an explicit hierarchy

### ISSUE THREAD

**Issue by davidwatkins73** [khartec/waltz#88]
i.e. 
| level1 | level2 | level 3 |

**Comment by davidwatkins73** [comment]
branch ```waltz-88-cap-hier```

**Comment by davidwatkins73** [comment]
Purpose of this change is to faciliate deeper capability trees.  By flattening the hierarchy queries will simplify as they need not be recursive or require table scans to build up a throw-away in memory tree.

**Comment by davidwatkins73** [comment]
-- backup existing capabilities
```
CREATE TABLE capability_bkp LIKE capability;
INSERT capability_bkp SELECT * FROM capability;
```

**Comment by kamransaleem** [comment]
Is this still applicable ?

**Comment by davidwatkins73** [comment]
No - it's been replaced by measurables
