### ISSUE TITLE
Pie: Setting to change layout

### ISSUE THREAD

**Issue by kamransaleem** [khartec/waltz#921]
- Stacked
- Adjacent

**Comment by davidwatkins73** [comment]
remind me where we wanted the adjacent option....

**Comment by kamransaleem** [comment]
On the pie table.  We want it stacked or adjacent

**Comment by davidwatkins73** [comment]
y, I meant what page did we want this to appear on ?

**Comment by davidwatkins73** [comment]
nm, remembered - it was for the technology stats - less vertical space used.

**Comment by kamransaleem** [comment]
The technology section. Org unit and other roll ups.
