### ISSUE TITLE
Indicator history table - square colours not displayed in IE

### ISSUE THREAD

**Issue by rovats** [khartec/waltz#935]
All squares are black:

![image](https://cloud.githubusercontent.com/assets/15289335/20173400/166e6032-a731-11e6-8b57-79c7d482bbf1.png)

**Comment by davidwatkins73** [comment]
This is often due to something like `class='prefix-{{$ctrl.suffix}}'`  which works in chrome/ff but not in IE.  Need to use `ng-class` instead.

**Comment by davidwatkins73** [comment]
Actually caused by using a `d3.rgb()` directly in a style.  It renders in a format that IE does not like.  Simple fix was to add `d3.rgb().toString()` which produces a hex value.

**Comment by davidwatkins73** [comment]
see #939

**Comment by rovats** [comment]
Ah yes, I did use `toString` initially but then removed it later..
