### ISSUE TITLE
tweak alignment of pie table indicators

### ISSUE THREAD

**Issue by davidwatkins73** [khartec/waltz#972]
![image](https://cloud.githubusercontent.com/assets/576829/20283605/8a48bb6e-aab1-11e6-86db-187c6e3bccbf.png)

**Comment by rovats** [comment]
Also, without a background, related indicators don't look that great..

**Comment by davidwatkins73** [comment]
y, will add a background for those.  I'll keep the 'group' page view ones as they are now.
