### ISSUE TITLE
Improve performance of logical flow stats calculation for Person view

### ISSUE THREAD

**Issue by rovats** [khartec/waltz#998]
`api/logical-flow/stats`

```
11:12:22.241 [http-apr-13401-exec-17] INFO  c.k.waltz.common.FunctionUtilities - -- dur [DFS.dataTypes]: 3766
11:12:26.400 [http-apr-13401-exec-17] INFO  c.k.waltz.common.FunctionUtilities - -- dur [DFSD.executeUnionAppCounters]: 4158
11:12:26.401 [http-apr-13401-exec-17] INFO  c.k.waltz.common.FunctionUtilities - -- dur [DFS.appCounts]: 4160
11:12:27.678 [http-apr-13401-exec-17] INFO  c.k.waltz.common.FunctionUtilities - -- dur [DFS.flowCounts]: 1277
```

**Comment by davidwatkins73** [comment]
Can have a go - though the join is huge as it's potentially against all people.....

**Comment by davidwatkins73** [comment]
Are we abandoning this ?

**Comment by rovats** [comment]
Let's keep it open, I'll have a look again.. at least of the queries can be simplified a bit without causing too much damage..

**Comment by rovats** [comment]
So far:

======================================================================
tallyDataTypesByAppIdSelector

-- dur [existing]:383
-- dur [existing]:225
-- dur [existing]:308
-- dur [existing]:239
-- dur [existing]:266

Avg: 284.2

-- dur [null check optimisation]:216
-- dur [null check optimisation]:145
-- dur [null check optimisation]:227
-- dur [null check optimisation]:169
-- dur [null check optimisation]:225

Avg: 196.4
======================================================================

======================================================================
countDistinctFlowInvolvementByAppIdSelector

-- result [existing]:LogicalFlowMeasures{inbound=2543.0, outbound=2493.0, intra=2736.0}
-- result [optimised]:LogicalFlowMeasures{inbound=2543.0, outbound=2493.0, intra=2736.0}

-- dur [existing]:350
-- dur [existing]:340
-- dur [existing]:355
-- dur [existing]:326
-- dur [existing]:326

Avg: 339.4

-- dur [optimised]:149
-- dur [optimised]:124
-- dur [optimised]:131
-- dur [optimised]:104
-- dur [optimised]:137

Avg: 129
======================================================================

Total:
Existing : 623.6
Optimised: 325.4

**Comment by rovats** [comment]
Now:

```
11:05:16.165 [DB Executor] INFO  c.k.waltz.common.FunctionUtilities - -- dur [DFS.flowCounts]: 963
11:05:16.504 [DB Executor] INFO  c.k.waltz.common.FunctionUtilities - -- dur [DFS.dataTypes]: 1305
11:05:19.896 [DB Executor] INFO  c.k.waltz.common.FunctionUtilities - -- dur [DFSD.executeUnionAppCounters]: 4694
11:05:19.899 [DB Executor] INFO  c.k.waltz.common.FunctionUtilities - -- dur [DFS.appCounts]: 4700
```
